function closeall(op)
%confirmation dialog for closing all figure windows
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.

if nargin == 0

   screenres = get(0,'ScreenSize');
   center = [screenres(3)./2 screenres(4)./2];

   h_dlg = figure('Name','Confirmation', ...
      'Visible','off', ...
      'Units','pixels', ...
      'Position',[center(1)-125 center(2)-40 250 80], ...
      'Menubar','none', ...
      'NumberTitle','off', ...
      'Resize','off', ...
      'DefaultUiControlUnits','normal', ...
      'KeypressFcn','closeall(''ok'')', ...
      'Tag','confirmclose', ...
      'UserData',gcf);

   bgcolor = get(h_dlg,'Color');

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[.05 .5 .9 .3], ...
      'String','Close all EEM plots?', ...
      'FontSize',12, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','center', ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0]);

   uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[.2 .1 .25 .3], ...
      'String','Cancel', ...
      'Callback','closeall(''cancel'')');

   uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[.55 .1 .25 .3], ...
      'String','OK', ...
      'FontWeight','bold', ...
      'Callback','closeall(''ok'')');

   set(h_dlg,'Visible','on')

else

   h_dlg = findobj('Tag','confirmclose');
   h_fig = get(h_dlg,'UserData');

   close(h_dlg)

   if strcmp(op,'cancel')

      figure(h_fig)

   elseif strcmp(op,'ok')

      h = findobj('Tag','eemplotfig');
      close(h)

   end

   drawnow

end
