function [eem_result,errormsg] = eem_math(expr,eems_in,matchopt,nanopt)
%syntax:  [eem_result,errormsg] = eem_math(expr,eems_in,matchopt,nanopt)
%
%Performs specified mathematical operations on fluorescence EEMs.
%
%'expr' is a text string containing a valid Matlab equation, with
%   individual EEMs represented as upper case letters.
%
%'eems_in' is a cell array containing one or more EEMs
%
%'matchopt' specifies how to handle matrix density mismatches.  If 'matchopt'
%   is 0 (default) the higher density matrices will be reduced to match the
%   lowest density matrix prior to division.  If 'matchopt' is 1 the lower
%   density matrices will promoted to match the highest density matrix
%   using bicubic interpolation.
%
%'nanopt' specifies how to handle NaN values in matrices.  If 'nanopt' is NaN
%   (default) NaN values will be retained, otherwise NaN values will be
%   replaced with the value specified.
%
%'eem_result' is a value or matrix containing the results of the operation
%
%Note:  the excitation/emission ranges and densities of EEMs will be matched
%using the 'matcheems.m' function prior to evaluating the expression.  Any
%error generated by evaluating the string will be trapped and returned along
%with an empty matrix.
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 3/8/2000

warning off
eem_result = [];
errormsg = '';
error = 0;

if nargin >= 2  %check for minimum arguments

   if isstr(expr) & iscell(eems_in)  %check for valid argument types

      %apply default values for omitted arguments
      if ~exist('matchopt')
         matchopt = 0;
      end
      if ~exist('nanopt')
         nanopt = NaN;
      end

      num = length(eems_in);  %counts EEMs

      %build array of lettered variable names
      if num <= 26

         varnames = char([65:65+num-1]');

      else

         %calculate max number letters (e.g. AAA=3)
         maxletters = fix((num-1)/26)+1;

         %produce full sets of single and multiple letters up to maxletters
         varnames = char([65:90]');
         for n = 2:maxletters
            varnames = str2mat(varnames,char(repmat([65:90]',1,n)));
         end

         %truncate variable names list
         varnames = varnames(1:num,:);

      end

      %convert padded character array to cell array
      varnames = cellstr(varnames);

      %run matrix matching function
      eems_in = matcheems(eems_in,matchopt);

      %perform variable assignments
      for n = 1:num
         if sum(size(eems_in{n})) > 2  %matrix
            [ex,em,fl] = unwrapeem(eems_in{n});
            if ~isnan(nanopt)
               fl(find(isnan(fl))) = nanopt;
            end
            eval([char(varnames{n}) ' = fl;'],'error = 1;')
         else  %scalar
            eval([char(varnames{n}) ' = eems_in{n};'],'error = 1;')
         end
      end

      %evaluate expression if assignments successful
      if error == 0
         eval(['result = ' expr ';'],'error = 1;')
         if error == 0
            if sum(size(result)~=size(fl)) == 0
               eem_result = wrapeem(ex,em,result);
            else
               eem_result = result;
            end
         end
      end

      %return error message if present
      if error == 1
         errormsg = lasterr;
      end

   else  %bad input type

      errormsg = 'One or more input arguments are invalid';

   end

else  %insufficient arguments

   errormsg = 'Too few arguments for function';

end
