function eeminfo(op,infostr)
%EEM information dialog called by 'eemplot'
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 11/2/1999

if strcmp(op,'init')

   h_fig = gcf;

   %prevent multiple instances of dialog
   h_dlg = findobj('Tag','dlgEEMInfo');
   if ~isempty(h_dlg)
      close(h_dlg)
   end

   if ~exist('infostr')
      infostr = {'no information available'};
      h_info = findobj(h_fig,'Tag','eeminfo');
      if ~isempty(h_info)
         infostr = get(h_info,'UserData');
      end
   end

   if length(infostr) < 8
      infostr = [infostr(:)' cell(1,8-length(infostr))];
   end

   res = get(0,'ScreenSize');
   bgcolor = [0.9 0.9 0.9];

   h_dlg = figure('Visible','off', ...
      'KeyPressFcn','eeminfo(''close'')', ...
      'Color',bgcolor, ...
      'MenuBar','none', ...
      'Name','EEM Information', ...
      'NumberTitle','off', ...
      'Position',[res(3)./2-225 res(4)./2-150 450 300], ...
      'Tag','dlgEEMInfo', ...
      'ToolBar','none', ...
      'Resize','off', ...
      'UserData',h_fig);

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 271 90 20], ...
      'String','Description:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 191 90 20], ...
      'String','Data Type:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 166 90 20], ...
      'String','Scan Date:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 141 90 20], ...
      'String','Excitation:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 116 90 20], ...
      'String','Emission:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 91 90 20], ...
      'String','Calibration:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 66 90 20], ...
      'String','Slit Settings:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'FontWeight','bold', ...
      'HorizontalAlignment','left', ...
      'Position',[6 41 90 20], ...
      'String','Dilution:', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 216 350 75], ...
      'Style','text', ...
      'String',char(infostr{1}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 191 350 20], ...
      'Style','text', ...
      'String',char(infostr{2}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 166 350 20], ...
      'Style','text', ...
      'String',char(infostr{3}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 141 350 20], ...
      'Style','text', ...
      'String',char(infostr{4}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 116 350 20], ...
      'Style','text', ...
      'String',char(infostr{5}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 91 350 20], ...
      'Style','text', ...
      'String',char(infostr{6}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 66 350 20], ...
      'Style','text', ...
      'String',char(infostr{7}));

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',10, ...
      'ForegroundColor',[0 0 .8], ...
      'HorizontalAlignment','left', ...
      'Position',[96 41 350 20], ...
      'Style','text', ...
      'String',char(infostr{8}));

   h1 = uicontrol('Parent',h_dlg, ...
      'Callback','eeminfo(''close'')', ...
      'FontWeight','bold', ...
      'Position',[195 2 60 25], ...
      'String','Close');

   set(h_dlg,'Visible','on')
   drawnow

elseif strcmp(op,'close')

   h_dlg = findobj('Tag','dlgEEMInfo');
   h_fig = get(h_dlg,'UserData');

   close(h_dlg)

   if ~isempty(h_fig)
      figure(h_fig)
   end

   drawnow

end