function h_s = eemplot(op,eemdata,limits,titlestr,zlabelstr,azel,axislims)
%syntax:  h_s = eemplot(plottype,eemdata,limits,titlestr,zlabelstr,azel,axislims)
%
%Perform 3d plot of fluorescence matrix and set standard appearance
%options.  'plottype' specifies whether to plot to a new figure with
%calculation control (plottype = 'newfig'), update an existing EEM plot
%(plottype = 'newplot') or to plot to a position on a scan layout page
%(plottype = 'slot#', where # = 1,2,3,4,6,9).
%
%Input arguments:
%
%'plottype' is the plot option ('newfig', etc.)
%
%'eemdata' is a matrix of EEM data, with excitation wavelengths in
%   the first row, emission wavelengths in the first column, and
%   corresponding fluorescence intensity values for each ex/em
%   wavelength combination.
%
%'limits' (optional) specifies a 1 or 2-element array of fluorescence axis limits
%
%'titlestr' (optional) specifies a custom plot title string.
%
%'zlabelstr' (optional) specifies a custom Z-axis label
%
%'azel' 2-element array of azimuth & elevation used to control the 3D view
%
%'axislims' 4-element array of excitation & emission (x/y) axis limits
%
%Output parameters:
%
%'h_s' graphics handle of the plot surface object
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 2/27/2007

if nargin > 0

   if strcmp(op(1,1:3),'new') | strcmp(op(1,1:3),'slo') %generate/update plot

      %process input arguments (apply defaults for missing values)
      [ex,em,fl] = unwrapeem(eemdata);

      if exist('limits') ~= 1
         limits = [];
      end

      if exist('titlestr') ~= 1
         titlestr = [];
      end

      if exist('zlabelstr') ~= 1
         zlabelstr = 'Fluorescence';
      elseif ~isstr(zlabelstr)
         zlabelstr = 'Fluorescence';
      end

      if exist('azel') ~= 1
         azel = [40 30];
      end

      if exist('axislims') ~= 1
         axislims = [min(ex) max(ex) min(em) max(em)];
      end

      %set up figure windows appropriately for plot type
      if strcmp(op(1,1:2),'sl')  %plot to a slot on page layout figure

         slotnum = str2num(op(1,5:length(op)));

         h_layout = findobj('Name','Page Layout');

         if isempty(h_layout)

            pagelayout('port',slotnum);
            pagelayout('activate',slotnum);

            h_layout = findobj('Name','Page Layout');

         end

         plotmatrix = get(h_layout,'UserData');

         fontmag = min(1,1.5./max(plotmatrix(1),plotmatrix(2)));

         if slotnum <= (plotmatrix(1) .* plotmatrix(2))
            subplot(plotmatrix(1),plotmatrix(2),slotnum)
         else
            subplot(plotmatrix(1),plotmatrix(2),(plotmatrix(1) .* plotmatrix(2)))
         end

      elseif strcmp(op,'newplot')  %plot new surface on existing figure

         if ~isempty(titlestr)
            set(gcf,'Name',titlestr)
         end

         fontmag = 1;

         h_ax = findobj(gcf,'Type','axes');

         delete(h_ax)

      else  %create new figure window and plot surface

         fontmag = 1;

         if ~isempty(titlestr)
            figtitle = titlestr;
         else
            figtitle = 'EEM Plot';
         end

         screen = get(0,'screensize');
         if screen(3) >= 800
            screenres = [(screen(3)-800)*.5 (screen(4)-600)*.5 800 600];
         else
            screenres = screen;
         end

         if exist('peaklabels.mat') == 2
            load peaklabels
         else
            peaklbls = [];
         end

         fig = figure('Units','pixels', ...
            'Position',[.035*screenres(3)+screenres(1) .05*screenres(4)+screenres(2) ...
               screenres(3) screenres(4)], ...
            'Color',[1 1 1], ...
            'InvertHardcopy','off', ...
            'PaperPositionMode','manual', ...
            'PaperType','usletter', ...
            'PaperOrientation','portrait', ...
            'PaperPosition',[0 1.25 8 7.5], ...
            'MenuBar','none', ...
            'NumberTitle','off', ...
            'Name',figtitle, ...
            'Tag','eemplotfig', ...
            'Visible','off');

         mnuFile = uimenu(fig,'Label','File');

         mnuView = uimenu(fig,'Label','View');

         mnuCalc = uimenu(fig,'Label','Calculations');

         mnuHelp = uimenu(fig,'Label','Help');

         mnuFileLoad = uimenu(mnuFile, ...
            'Label','Load EEM', ...
            'Tag','pathcache', ...
            'UserData',[]);

         mnuFileLoadUp = uimenu(mnuFileLoad, ...
            'Label','Same Figure');

         mnuFileLoadNew = uimenu(mnuFileLoad, ...
            'Label','New Figure');

         uimenu(mnuFileLoadUp, ...
            'Label','Current View', ...
            'Callback','loadscan(''update'');');

         uimenu(mnuFileLoadUp, ...
            'Label','Original View as Saved', ...
            'Callback','loadscan(''newplot'');');

         uimenu(mnuFileLoadNew, ...
            'Label','Single Plot', ...
            'Callback','loadscan;');

         uimenu(mnuFileLoadNew, ...
            'Label','Multiple Plots', ...
            'Callback','multiload;');

         uimenu(mnuFile, ...
            'Label','Save EEM', ...
            'Callback','savescan;');

         mnuFileImport = uimenu(mnuFile, ...
            'Label','Import EEM', ...
            'Separator','on');

         mnuFileImpMat = uimenu(mnuFileImport, ...
            'Label','EEM Variable (Matlab File)');

         mnuFileImpMatNew = uimenu(mnuFileImpMat, ...
            'Label','Same Figure');

         uimenu(mnuFileImpMatNew, ...
            'Label','Update Data Only', ...
            'Callback','dataplot(''surfupdate'')');

         uimenu(mnuFileImpMatNew, ...
            'Label','New Plot', ...
            'Callback','dataplot(''surfnewplot'')');

         uimenu(mnuFileImpMat, ...
            'Label','New Figure', ...
            'Callback','dataplot(''surfnewfig'')');

         mnuFileExport = uimenu(mnuFile, ...
            'Label','Export Plot');

         mnuFileExportData = uimenu(mnuFile, ...
            'Label','Export Data');

         uimenu(mnuFileExport, ...
            'Label','Copy to Clipboard', ...
            'Callback','printeem(''clipboard'')');

         mnuFileExpPS = uimenu(mnuFileExport, ...
            'Separator','on', ...
            'Label','Postscript file');

         mnuFileExpJpeg = uimenu(mnuFileExport, ...
            'Label','JPeg file');

         mnuFileExpTiff = uimenu(mnuFileExport, ...
            'Label','TIFF file');

         uimenu(mnuFileExpPS, ...
            'Label','Postscript (color)', ...
            'Callback','exportfig(''psc'')');

         uimenu(mnuFileExpPS, ...
            'Label','Postscript (monochrome)', ...
            'Callback','exportfig(''psbw'')');

         uimenu(mnuFileExpPS, ...
            'Label','EPS level 2 (color)', ...
            'Callback','exportfig(''epsc2'')');

         uimenu(mnuFileExpPS, ...
            'Label','EPS level 2 (monochrome)', ...
            'Callback','exportfig(''epsbw2'')');

         uimenu(mnuFileExpPS, ...
            'Label','EPS level 1 (color)', ...
            'Callback','exportfig(''epsc1'')');

         uimenu(mnuFileExpPS, ...
            'Label','EPS level 1 (monochrome)', ...
            'Callback','exportfig(''epsbw1'')');

         uimenu(mnuFileExpJpeg, ...
            'Label','High Resolution (300dpi)', ...
            'Callback','exportfig(''jpeghigh'')');

         uimenu(mnuFileExpJpeg, ...
            'Label','Normal Resolution (150dpi)', ...
            'Callback','exportfig(''jpegmed'')');

         uimenu(mnuFileExpJpeg, ...
            'Label','Low Resolution (72 dpi)', ...
            'Callback','exportfig(''jpeglow'')');

         uimenu(mnuFileExpTiff, ...
            'Label','High Resolution, Compressed (300dpi)', ...
            'Callback','exportfig(''tiffhc'')');

         uimenu(mnuFileExpTiff, ...
            'Label','High Resolution, Uncompressed (300dpi)', ...
            'Callback','exportfig(''tiffhnc'')');

         uimenu(mnuFileExpTiff, ...
            'Label','Medium Resolution, Compressed (150dpi)', ...
            'Callback','exportfig(''tiffmc'')');

         uimenu(mnuFileExpTiff, ...
            'Label','Medium Resolution, Uncompressed (150dpi)', ...
            'Callback','exportfig(''tiffmnc'')');

         uimenu(mnuFileExport, ...
            'Label','Matlab Plot File', ...
            'Callback','exportfig(''mfile'')');

         uimenu(mnuFileExportData, ...
            'Label','ASCII matrix (spreadsheet)', ...
            'Callback','exportascii([],''matrix'')');

         uimenu(mnuFileExportData, ...
            'Label','ASCII XYZ triplets (plotting program)', ...
            'Callback','exportascii([],''xyz'')');

         mnuFilePrint = uimenu(mnuFile, ...
            'Label','Print', ...
            'Separator','on');

         uimenu(mnuFilePrint, ...
            'Label','Full Page (Portrait)', ...
            'Callback','printeem fullport');

         uimenu(mnuFilePrint, ...
            'Label','Top Half (Portrait)', ...
            'Callback','printeem topport');

         uimenu(mnuFilePrint, ...
            'Label','Bottom Half (Portrait)', ...
            'Callback','printeem bottomport');

         uimenu(mnuFile, ...
            'Label','Page Setup', ...
            'Callback','pagedlg');

         uimenu(mnuFile, ...
            'Label','Print Preview', ...
            'Callback','printpreview');

         uimenu(mnuFile, ...
            'Label','Close', ...
            'Separator','on', ...
            'Callback','close(gcf); drawnow');

         uimenu(mnuFile, ...
            'Label','Close All', ...
            'Callback','closeall');

         uimenu(mnuView, ...
            'Label','Axis Properties', ...
            'Tag','axlims', ...
            'UserData',[], ...
            'Callback','newaxisdlg');

         uimenu(mnuView, ...
            'Label','Surface Properties', ...
            'Callback','surfoptdlg');

         uimenu(mnuView, ...
            'Label','Figure Colors', ...
            'Callback','figcolors');

         uimenu(mnuView, ...
            'Label','Change Axis Font', ...
            'Callback','uisetfont(gca);', ...
            'Separator','on');

         uimenu(mnuView, ...
            'Label','Change Colorbar Font', ...
            'Callback','h_cbar=findobj(gcf,''type'',''axes'',''tag'',''Colorbar''); if ~isempty(h_cbar); uisetfont(h_cbar); end');

         mnuViewContour = uimenu(mnuView, ...
            'Label','Contour Lines', ...
            'Separator','on', ...
            'Tag','contouropt', ...
            'UserData',[{[]} {[0 0 0]} {8}]);

         mnuViewConShow = uimenu(mnuViewContour, ...
            'Label','Display/Edit Contour Lines', ...
            'Tag','contourshow', ...
            'Checked','off', ...
            'UserData',[{[]} {[]} {[]}], ...
            'Callback','contourlines(''dialog'')');

         uimenu(mnuViewContour, ...
            'Label','Remove Contour Lines', ...
            'Tag','contourhide', ...
            'Checked','on', ...
            'Callback','contourlines(''clear'')');

         mnuViewPeak = uimenu(mnuView, ...
            'Label','Peak Labels', ...
            'Tag','peaklabelopt', ...
            'UserData',peaklbls);

         mnuViewPeakDisp = uimenu(mnuViewPeak, ...
            'Label','Display/Edit Peak Labels', ...
            'Tag','showpeaklabels', ...
            'Callback','editpeaks(''init'');');

         uimenu(mnuViewPeak, ...
            'Label','Remove Peak Labels', ...
            'Checked','on', ...
            'Tag','hidepeaklabels', ...
            'Callback','editpeaks(''hide'');');

         uimenu(mnuView, ...
            'Label','Hide Grid Lines', ...
            'Tag','hidegrid', ...
            'Callback','plottoggle(''grid'')');

         uimenu(mnuView, ...
            'Label','Hide Color Bar', ...
            'Tag','hidecbar', ...
            'Callback','plottoggle(''cbar'');');

         mnuViewColor = uimenu(mnuView, ...
            'Label','Change Colormap', ...
            'Separator','on', ...
            'Tag','colormap', ...
            'UserData',[{'jet(128)'} {1}]);

         uimenu(mnuView, ...
            'Label','Reverse Colormap', ...
            'Tag','revcmap', ...
            'Callback','newcolor(''cmap_rev'')');

         uimenu(mnuView, ...
            'Label','Hide Plot Controls', ...
            'Separator','on', ...
            'Tag','uihide', ...
            'Callback','viewcontrols(''hide'')');

         uimenu(mnuView, ...
            'Label','Free Rotate Mode', ...
            'Tag','viewmode', ...
            'Callback','plottoggle(''view'')');

         uimenu(mnuViewColor, ...
            'Label','Jet (blue-green-red)', ...
            'Checked','on', ...
            'Tag','cmap_jet(128)', ...
            'Callback','newcolor(''cmap_jet(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Hue-Saturation Value', ...
            'Checked','off', ...
            'Tag','cmap_hsv(128)', ...
            'Callback','newcolor(''cmap_hsv(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Hot (black-red-white)', ...
            'Checked','off', ...
            'Tag','cmap_hot(128)', ...
            'Callback','newcolor(''cmap_hot(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Cool (aqua-blue-purple)', ...
            'Checked','off', ...
            'Tag','cmap_cool(128)', ...
            'Callback','newcolor(''cmap_cool(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Gray (linear gray scale)', ...
            'Checked','off', ...
            'Tag','cmap_gray(128)', ...
            'Callback','newcolor(''cmap_gray(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Bone (gray scale - bluish)', ...
            'Checked','off', ...
            'Tag','cmap_bone(128)', ...
            'Callback','newcolor(''cmap_bone(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Copper (linear copper-tone)', ...
            'Checked','off', ...
            'Tag','cmap_copper(128)', ...
            'Callback','newcolor(''cmap_copper(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Pink (pastel pinks)', ...
            'Checked','off', ...
            'Tag','cmap_pink(128)', ...
            'Callback','newcolor(''cmap_pink(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Spring (magenta and yellow)', ...
            'Checked','off', ...
            'Tag','cmap_spring(128)', ...
            'Callback','newcolor(''cmap_spring(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Summer (blue and green)', ...
            'Checked','off', ...
            'Tag','cmap_summer(128)', ...
            'Callback','newcolor(''cmap_summer(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Autumn (red and yellow)', ...
            'Checked','off', ...
            'Tag','cmap_autumn(128)', ...
            'Callback','newcolor(''cmap_autumn(128)'')');

         uimenu(mnuViewColor, ...
            'Label','Winter (green and yellow)', ...
            'Checked','off', ...
            'Tag','cmap_winter(128)', ...
            'Callback','newcolor(''cmap_winter(128)'')');

         mnuIntSurf = uimenu(mnuCalc, ...
            'Label','Surface Integration');

         uimenu(mnuIntSurf, ...
            'Label','Interactive Integration', ...
            'Callback','surfintegrate');

         uimenu(mnuIntSurf, ...
            'Label','Multiple Integrations', ...
            'Tag','surfintmulti', ...
            'UserData',[], ...
            'Callback','surfintmulti');

         mnuIntSingle = uimenu(mnuCalc, ...
            'Label','Single Wavelength Integration');

         uimenu(mnuIntSingle, ...
            'Label','Emission Scans', ...
            'Callback','exem_plot(''em'')');

         uimenu(mnuIntSingle, ...
            'Label','Excitation Scans', ...
            'Callback','exem_plot(''ex'')');

         uimenu(mnuHelp, ...
            'Label','Toolbox Window', ...
            'Callback','fltoolbox');

         uimenu(mnuHelp, ...
            'Label','EEM Information', ...
            'Separator','on', ...
            'Callback','eeminfo(''init'')', ...
            'Tag','eeminfo', ...
            'UserData',[{'no information available'}]);

      end

      %generate surface plot
      h_s = surf(ex,em,fl);

      %apply default appearance options
      set(h_s, ...
         'FaceColor','interp', ...
         'EdgeColor','none', ...
         'LineWidth',.1, ...
         'EdgeLighting','gouraud', ...
         'FaceLighting','gouraud', ...
         'BackFaceLighting','reverselit')

      set(gca, ...
         'Color',[.9 .9 .9], ...
         'FontSize',12.*fontmag)

      if ~isempty(limits)
         ax = axis;
         cur_caxis = clim;
         if length(limits) == 2
            axis([ax(1,1:4) limits])
            clim(limits)
         elseif length(limits) == 1
            axis([ax(1,1:4) limits ax(1,6)])
            clim([limits ax(1,6)])
         end
      else
         zlims = get(gca,'ZLim');
         clim(zlims);
      end

      if ~isempty(titlestr)
         h_title = get(gca,'Title');
         set(h_title, ...
            'String',titlestr, ...
            'FontName','Times New Roman', ...
            'FontSize',max(10,min(20,round(1000 ./ length(titlestr))).*fontmag), ...
            'FontWeight','bold', ...
            'Interpreter','none', ...
            'ButtonDownFcn','textedit')
      end

      h_xlabel = get(gca,'Xlabel');

      set(h_xlabel, ...
         'String','Excitation (nm)', ...
         'Fontsize',11.*fontmag, ...
         'Fontweight','bold', ...
         'Interpreter','none', ...
         'ButtonDownFcn','textedit')

      h_ylabel = get(gca,'Ylabel');

      set(h_ylabel, ...
         'String','Emission (nm)', ...
         'Fontsize',11.*fontmag, ...
         'Fontweight','bold', ...
         'Interpreter','none', ...
         'ButtonDownFcn','textedit')

      h_zlabel = get(gca,'Zlabel');

      set(h_zlabel, ...
         'String',zlabelstr, ...
         'Fontsize',11.*fontmag, ...
         'Fontweight','bold', ...
         'Interpreter','none', ...
         'ButtonDownFcn','textedit')

      colormap(jet(128))

      if ~isempty(axislims)
         if length(axislims) == 4 | length(axislims) == 6
            if length(axislims) == 4
               axislims = [axislims get(gca,'ZLim')];
            end
            axis(axislims)
         end
      end

      %create colorbar, adjust axis/colorbar size and position
      h_axis = gca;
      h_bar = colorbar;
      axes(h_axis);  %reset current axis pointer

      axpos = get(h_axis,'Position');
      cbarpos = get(h_bar,'Position');
      cbarht = axpos(4)*0.7;

      if mlversion >= 7
         hoffset = -.1;
      else
         hoffset = 0;
      end
      set(h_bar, ...
         'Position',[cbarpos(1)+hoffset axpos(2)+(axpos(4)-cbarht).*0.5 cbarpos(3) cbarht], ...
         'FontSize',9.*fontmag)

      grid on

      set(gcf,'Visible','on')

      %newaxis

      h_axlims = findobj(gcf,'Tag','axlims');

      xlims = get(gca,'XLim');
      ylims = get(gca,'YLim');
      zlims = get(gca,'ZLim');

      ax_incvals = [1 2 3 5];
      for n = 1:6
         ax_incvals = [ax_incvals ax_incvals.*10^n];
      end

      num_xyincs = repmat(max(diff(ylims),diff(xlims)),1,length(ax_incvals)) ./ ax_incvals;
      I_bestxy = find(num_xyincs>=4 & num_xyincs<=10);

      num_zincs = repmat(diff(zlims),1,length(ax_incvals)) ./ ax_incvals;
      I_bestz = find(num_zincs>=4 & num_zincs<=10);

      if ~isempty(I_bestxy)

         xy_inc = fliplr(ax_incvals(I_bestxy));

         div = repmat(xlims(1),1,length(xy_inc)) ./ xy_inc;

         I_whole = find(div == fix(div));
         if isempty(I_whole)
            div = repmat(ylims(1),1,length(xy_inc)) ./ xy_inc;
            I_whole = find(div == fix(div));
            if isempty(I_whole)
               div = repmat(xlims(2),1,length(xy_inc)) ./ xy_inc;
               I_whole = find(div == fix(div));
               if isempty(I_whole)
                  div = repmat(ylims(2),1,length(xy_inc)) ./ xy_inc;
                  I_whole = find(div == fix(div));
               end
            end
         end

         if ~isempty(I_whole)
            xy_inc = xy_inc(I_whole(1));
            xticks = [ceil(xlims(1)./xy_inc)*xy_inc:xy_inc:xlims(2)];
            yticks = [ceil(ylims(1)./xy_inc)*xy_inc:xy_inc:ylims(2)];
         else
            xticks = get(gca,'XTick');
            yticks = get(gca,'YTick');
         end

      else
         xticks = get(gca,'XTick');
         yticks = get(gca,'YTick');
      end

      if ~isempty(I_bestz)

         z_inc = fliplr(ax_incvals(I_bestz));
         div = repmat(zlims(1),1,length(z_inc)) ./ z_inc;

         I_whole = find(div == fix(div));
         if isempty(I_whole)
            div = repmat(zlims(2),1,length(z_inc)) ./ z_inc;
            I_whole = find(div == fix(div));
         end

         if ~isempty(I_whole)
            z_inc = z_inc(I_whole(1));
            zticks = [ceil(zlims(1)./z_inc)*z_inc:z_inc:zlims(2)];
         else
            zticks = get(gca,'ZTick');
         end

      else
         zticks = get(gca,'ZTick');
      end

      if length(zticks) < 2
         zticks = zlims;
      end

      set(gca, ...
         'XTick',xticks, ...
         'YTick',yticks, ...
         'ZTick',zticks)

      set(h_axlims,'UserData', ...
         [xlims xticks(1) xticks(2)-xticks(1) ...
         ylims yticks(1) yticks(2)-yticks(1) ...
         zlims zticks(1) zticks(2)-zticks(1)])

      if strcmp(op,'newfig')

         viewcontrols

         viewcontrols axislabels

      elseif strcmp(op,'newplot')

         axpos = get(gca,'Position');
         set(gca, ...
            'Position',[axpos(1)+0.07 axpos(2)+.07 axpos(3) axpos(4)-.07])

         if mlversion < 7
            barpos = get(h_bar,'Position');
            set(h_bar,'Position',[barpos(1)+0.05 axpos(2)+.07 barpos(3) axpos(4)-.07])
         end

      end

      if azel(2) == 90 & (azel(1) == 0 | azel(1) == 180)
         viewcontrols top
      else
         view(azel)
      end

      %(place other callbacks below)
      %else

   end

end

