function eemulator(op)
%Fluorescence EEM calculator/emulator toolbox function
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 2/27/2007

if nargin == 0
   op = 'init';
end

if strcmp(op,'init')

   h_dlg = findobj('Tag','dlgEEMulator');

   if ~isempty(h_dlg)  %avoid duplicate windows/callback errors

      figure(h_dlg)

   else

      %load default equation templates
      if exist('eemulator.mat') == 2
         load eemulator.mat
      end

      if exist('templates') == 1  %use templates in pref file

         templatestr = templates{1,1};
         for n = 2:size(templates,1)
            templatestr = [templatestr '|' deblank(char(templates(n,1)))];
         end

      else  %use default template list

         templates = [{'None'},{['%define intermediate terms using lowercase letters, ' ...
                     'numbers, symbols, and C# placeholders']},{''}];
         templatestr = 'None';

      end

      if exist('options') ~= 1  %options struct doesn't exist in pref file

         %create option struct
         options = struct('maxerows',25, ...
            'maxcrows',25', ...
            'hilite',[1 1 .5], ...
            'matchopt',1, ...
            'autoplot',1);

      end

      screenres = get(0,'screensize');

      %create dialog
      h_dlg = figure('Name','EEMulator', ...
         'Visible','off', ...
         'Renderer','zbuffer', ...
         'Position',[screenres(3)-566 max(50,(screenres(4)-560)./2) 561 520], ...
         'Color',[.88 .88 .88], ...
         'KeyPressFcn','figure(gcf)', ...
         'MenuBar','none', ...
         'ToolBar','none', ...
         'NumberTitle','off', ...
         'Resize','off', ...
         'Tag','dlgEEMulator', ...
         'DefaultUicontrolUnits','pixels', ...
         'UserData',[]);

      axis off

      %define general command buttons
      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[3 491 60 25], ...
         'String','Load', ...
         'Tag','cmdLoadWS', ...
         'Callback',['confirmdlg(''init'',''Load Workspace? (overwrites existing variables and settings)'',' ...
            '''eemulator(''''wsload'''')'')'], ...
         'TooltipString','Load variables and equation from workspace file');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[65 491 60 25], ...
         'String','Save', ...
         'Tag','cmdSaveWS', ...
         'Callback','eemulator(''wssave'')', ...
         'TooltipString','Save variables and equation as workspace file');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[127 491 60 25], ...
         'String','Add', ...
         'Tag','cmdAdd', ...
         'CallBack','eemulator(''add'')', ...
         'TooltipString','Add EEM data in a file to the variables list');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[189 491 60 25], ...
         'String','Remove', ...
         'Tag','cmdRemove', ...
         'CallBack','eemulator(''remove'')', ...
         'TooltipString','Remove highlighted EEM from variables list');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[251 491 60 25], ...
         'String','Compact', ...
         'Tag','cmdCompact', ...
         'CallBack','eemulator(''compact'')', ...
         'TooltipString','Compact variable lists to remove empty slots');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[313 491 60 25], ...
         'String','View', ...
         'Tag','cmdView', ...
         'Callback','eemulator(''view'')', ...
         'TooltipString','View highlighted EEM as surface plot');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[375 491 60 25], ...
         'String','Options', ...
         'Tag','cmdOptions', ...
         'Callback','eemulator(''options'')', ...
         'UserData',options, ...
         'TooltipString','Set EEM calculation and display options');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[437 491 60 25], ...
         'String','Reset', ...
         'Tag','cmdReset', ...
         'CallBack','confirmdlg(''init'',''Clear all fields?'',''eemulator(''''reset'''')'')', ...
         'TooltipString','Clear all fields');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[499 491 60 25], ...
         'String','Close', ...
         'Tag','cmdClose', ...
         'CallBack',['confirmdlg(''init'',''Close EEMulator? (data will not be saved)'',' ...
            '''eemulator(''''close'''')'')'], ...
         'TooltipString','Close EEMulator window');

      %create variables controls
      h_vars = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.8 0.8 0.8], ...
         'FontWeight','bold', ...
         'ForegroundColor',[0.8 0 0], ...
         'Max',2, ...
         'Position',[7 468 415 18], ...
         'String','EEM Variables', ...
         'Style','text', ...
         'Tag','txtVars');

      h_le1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 440 40 20], ...
         'String','E1', ...
         'Style','text', ...
         'Tag','txtE1', ...
         'UserData',1);

      h_le2 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 410 40 20], ...
         'String','E2', ...
         'Style','text', ...
         'Tag','txtE2');

      h_le3 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 380 40 20], ...
         'String','E3', ...
         'Style','text', ...
         'Tag','txtE3');

      h_le4 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 350 40 20], ...
         'String','E4', ...
         'Style','text', ...
         'Tag','txtE4');

      h_le5 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 320 40 20], ...
         'String','E5', ...
         'Style','text', ...
         'Tag','txtE5');

      h_e1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[46 441 345 22], ...
         'String','', ...
         'Style','edit', ...
         'Enable','off', ...
         'Tag','editE1', ...
         'UserData',cell(options.maxerows,1), ...
         'ButtonDownFcn','eemulator(''var1'')');

      h_e2 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[46 411 345 22], ...
         'Style','edit', ...
         'Enable','off', ...
         'Tag','editE2', ...
         'ButtonDownFcn','eemulator(''var2'')');

      h_e3 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[46 381 345 22], ...
         'Style','edit', ...
         'Enable','off', ...
         'Tag','editE3', ...
         'ButtonDownFcn','eemulator(''var3'')');

      h_e4 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[46 351 345 22], ...
         'Style','edit', ...
         'Enable','off', ...
         'Tag','editE4', ...
         'ButtonDownFcn','eemulator(''var4'')');

      h_e5 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[46 321 345 22], ...
         'Style','edit', ...
         'Enable','off', ...
         'Tag','editE5', ...
         'ButtonDownFcn','eemulator(''var5'')');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0 0 0], ...
         'Max',options.maxerows-4, ...
         'Min',1, ...
         'SliderStep',[1./(options.maxerows-5) 5./(options.maxerows-5)], ...
         'Position',[397 320 20 145], ...
         'Style','slider', ...
         'Tag','slrE', ...
         'Callback','eemulator(''slidv'')', ...
         'UserData',1, ...
         'Value',options.maxerows-4);

      %create constants control group
      h_const = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.8 0.8 0.8], ...
         'FontWeight','bold', ...
         'ForegroundColor',[0.8 0 0], ...
         'Position',[427 468 130 18], ...
         'String','User Constants', ...
         'Style','text', ...
         'Tag','txtConst');

      h_lc1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[426 440 40 20], ...
         'String','C1', ...
         'Style','text', ...
         'Tag','txtC1', ...
         'UserData',1);

      h_lc2 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[426 410 40 20], ...
         'String','C2', ...
         'Style','text', ...
         'Tag','txtC2');

      h_lc3 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[426 380 40 20], ...
         'String','C3', ...
         'Style','text', ...
         'Tag','txtC3');

      h_lc4 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[426 350 40 20], ...
         'String','C4', ...
         'Style','text', ...
         'Tag','txtC4');

      h_lc5 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[426 320 40 20], ...
         'String','C5', ...
         'Style','text', ...
         'Tag','txtC5');

      h_c1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[466 440 60 22], ...
         'Style','edit', ...
         'Tag','editC1', ...
         'UserData',cell(options.maxcrows,1), ...
         'Callback','eemulator(''con1'')');

      h_c2 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[466 411 60 22], ...
         'Style','edit', ...
         'Tag','editC2', ...
         'Callback','eemulator(''con2'')');

      h_c3 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[466 381 60 22], ...
         'Style','edit', ...
         'Tag','editC3', ...
         'Callback','eemulator(''con3'')');

      h_c4 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[466 351 60 22], ...
         'Style','edit', ...
         'Tag','editC4', ...
         'Callback','eemulator(''con4'')');

      h_c5 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Position',[466 321 60 22], ...
         'Style','edit', ...
         'Tag','editC5', ...
         'Callback','eemulator(''con5'')');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0 0 0], ...
         'Max',options.maxcrows-4, ...
         'Min',1, ...
         'SliderStep',[1./(options.maxcrows-5) 5./(options.maxcrows-5)], ...
         'Position',[532 321 20 145], ...
         'Style','slider', ...
         'Tag','slrC', ...
         'Callback','eemulator(''slidc'')', ...
         'UserData',1, ...
         'Value',options.maxcrows-4);

      %create EEM info fields
      h_info = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.8 0.8 0.8], ...
         'FontWeight','bold', ...
         'ForegroundColor',[0.8 0 0], ...
         'Position',[6 297 550 18], ...
         'String','Current EEM Information', ...
         'Style','text', ...
         'Tag','txtInfo');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[11 274 63 18], ...
         'String','Description', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[11 232 63 18], ...
         'String','EEM Type', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[11 214 63 18], ...
         'String','Scan Date', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[11 196 63 18], ...
         'String','Calibration', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[266 232 63 18], ...
         'String','Excitation', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[266 214 63 18], ...
         'String','Emission', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[266 196 63 18], ...
         'String','Slit Settings', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[440 232 55 18], ...
         'String','Dilution', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[440 214 55 18], ...
         'String','Raman Ref', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'ForegroundColor',[0 0 0.8], ...
         'HorizontalAlignment','left', ...
         'Position',[440 196 55 18], ...
         'String','Raman', ...
         'Style','text');

      h_i1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Max',2, ...
         'Position',[76 256 475 38], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtDesc');

      h_i2 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[76 232 180 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtDataType');

      h_i3 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[76 214 180 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtScanDate');

      h_i4 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[76 196 185 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtCalibration');

      h_i5 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[331 232 105 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtExcitation');

      h_i6 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[331 214 105 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtEmission');

      h_i7 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[331 196 105 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtSlits');

      h_i8 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[508 232 52 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtDilution');

      h_i9 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[508 214 52 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtRamanWave');

      h_i10 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'HorizontalAlignment','left', ...
         'Position',[508 196 52 18], ...
         'String','', ...
         'Style','text', ...
         'Tag','txtRaman');

      %create equation control group
      h_eqedit = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.8 0.8 0.8], ...
         'FontWeight','bold', ...
         'ForegroundColor',[0.8 0 0], ...
         'Position',[6 175 550 18], ...
         'String','Equation Editor', ...
         'Style','text', ...
         'Tag','txtEqEdit');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 147 55 20], ...
         'FontSize',9, ...
         'HorizontalAlignment','left', ...
         'String','Template', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'Position',[62 147 250 22], ...
         'FontSize',9, ...
         'String',templatestr, ...
         'Style','popupmenu', ...
         'Tag','popTemplate', ...
         'UserData',templates, ...
         'Callback','eemulator(''template'')', ...
         'TooltipString','Select a predefined equation template', ...
         'Value',1);

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 122 55 20], ...
         'HorizontalAlignment','left', ...
         'FontSize',9, ...
         'String','Definitions', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[0.9 0.9 0.9], ...
         'Position',[6 4 55 20], ...
         'FontSize',9, ...
         'String','EEM = ', ...
         'Style','text');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Min',0, ...
         'Max',2, ...
         'FontSize',9, ...
         'Position',[62 29 430 115], ...
         'Style','edit', ...
         'String',templates{1,2}, ...
         'Tag','editTerms');

      h1 = uicontrol('Parent',h_dlg, ...
         'BackgroundColor',[1 1 1], ...
         'HorizontalAlignment','left', ...
         'Min',0, ...
         'Max',1, ...
         'FontSize',9, ...
         'Position',[62 5 430 22], ...
         'Style','edit', ...
         'String',templates{1,3}, ...
         'Tag','editEquation');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[500 134 50 25], ...
         'String','Name', ...
         'Tag','cmdNameTemp', ...
         'Callback','eemulator(''temp_name'')', ...
         'TooltipString','Name current equation and save as template');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[500 96 50 25], ...
         'String','Delete', ...
         'Tag','cmdEdit', ...
         'Callback',['confirmdlg(''init'',''Delete current template from list?'',' ...
            '''eemulator(''''temp_delete'''')'')'], ...
         'TooltipString','Delete current template from list');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[500 58 50 25], ...
         'String','Test', ...
         'Tag','cmdTest', ...
         'Callback','eemulator(''eqtest'')', ...
         'TooltipString','Test expression for Matlab syntax errors');

      h1 = uicontrol('Parent',h_dlg, ...
         'Position',[500 20 50 25], ...
         'String','Evaluate', ...
         'Tag','cmdEval', ...
         'Callback','eemulator(''eqeval'')', ...
         'TooltipString','Evaluate expression and form calculated EEM');

      set(h_dlg,'Visible','on')
      drawnow

      %save editbox handles
      set(h_vars,'UserData',[h_le1 h_le2 h_le3 h_le4 h_le5; h_e1 h_e2 h_e3 h_e4 h_e5])
      set(h_const,'UserData',[h_lc1 h_lc2 h_lc3 h_lc4 h_lc5; h_c1 h_c2 h_c3 h_c4 h_c5])
      set(h_info,'UserData',[h_i1 h_i2 h_i3 h_i4 h_i5 h_i6 h_i7 h_i8 h_i9 h_i10])

   end

else

   h_dlg = findobj('Tag','dlgEEMulator');

   %get cell array of EEM data
   h_e1 = findobj(h_dlg,'Tag','editE1');
   eems = get(h_e1,'UserData');

   %get toprow of visible variables
   h_slv = findobj(h_dlg,'Tag','slrE');
   toprow = get(h_slv,'UserData');

   %get current row
   h_le1 = findobj(h_dlg,'Tag','txtE1');
   r = get(h_le1,'UserData');

   if strcmp(op,'close')  %close dialog window

      %close residual subdialogs
      h = findobj('Tag','dlgNameEEM');
      if ~isempty(h)
         close(h)
      end
      h = findobj('Tag','dlgOptions');
      if ~isempty(h)
         close(h)
      end

      %close main window
      close(h_dlg)

   elseif strcmp(op(1,1:3),'sli')  %handle slider clicks

      if strcmp(op,'slidv')  %EEM variable slider
         h_slr = h_slv;
         curtop = toprow;
         currow = r;
      else  %user constants slider
         h_slr = findobj(h_dlg,'Tag','slrC');
         curtop = get(h_slr,'UserData');
         h_lc1 = findobj(h_dlg,'Tag','txtC1');
         currow = get(h_lc1,'UserData');
      end

      val = round(get(h_slr,'Value'));
      newtop = get(h_slr,'Max') + 1 - val;
      scroll = newtop - curtop;

      if scroll ~= 0  %scroll event

         set(h_slr,'UserData',newtop)

         if strcmp(op,'slidv')  %EEM variable slider
            set(h_le1,'UserData',min(max(currow-scroll,1),5))
            eemulator('scrolle')
         else
            set(h_lc1,'UserData',min(max(currow-scroll,1),5))
            eemulator('scrollc')
         end

      end

   elseif strcmp(op,'scrolle')  %scroll EEM variable list

      %get uicontrol handles
      h_vars = findobj(h_dlg,'Tag','txtVars');
      h = get(h_vars,'UserData');

      %get stored options
      h_options = findobj(h_dlg,'Tag','cmdOptions');
      options = get(h_options,'UserData');

      %initialize cell arrays for strings
      descstr = cell(5,1);
      lblstr = cell(5,1);

      for n = 1:5  %build value arrays

         rownum = toprow + n - 1;
         eem = eems{rownum};

         if ~isempty(eem)
            descstr{n} = eem.description(1,:);
         else
            descstr{n} = '';
         end

         lblstr{n} = ['E' int2str(rownum)];

      end

      %update editboxes
      set(h(2,:),[{'String'},{'BackgroundColor'}],[descstr repmat({[1 1 1]},5,1)])
      set(h(2,r),'BackgroundColor',options.hilite)  %highlight current variable
      drawnow
      set(h(1,:),{'String'},lblstr)
      drawnow

      eemulator(['info' int2str(r)])  %update info field

   elseif strcmp(op,'scrollc')  %scroll User Constants list

      %get editbox handles
      h_const = findobj(h_dlg,'Tag','txtConst');
      h = get(h_const,'UserData');

      %get user const array
      h_c1 = findobj(h_dlg,'Tag','editC1');
      cdata = get(h_c1,'UserData');

      %get toprow
      h_slrc = findobj(h_dlg,'Tag','slrC');
      ctop = get(h_slrc,'UserData');

      for n = 1:5

         rownum = ctop + n - 1;
         set(h(1,n),'String',['C' int2str(rownum)])

         if ~isempty(cdata{rownum})
            set(h(2,n),'String',num2str(cdata{rownum}))
         else
            set(h(2,n),'String','')
         end

      end

      drawnow

   elseif strcmp(op(1,1:3),'var')  %update current variable field

      r = str2num(op(1,4));  %update current row via argument parsing

      h_le1 = findobj(h_dlg,'Tag','txtE1');

      h_options = findobj(h_dlg,'Tag','cmdOptions');
      options = get(h_options,'UserData');

      h_vars = findobj(h_dlg,'Tag','txtVars');
      h = get(h_vars,'UserData');

      set(h_le1,'UserData',r)  %update cached current row
      set(h(2,:),'BackgroundColor',[1 1 1])  %reset editbox backgrounds
      set(h(2,r),'BackgroundColor',options.hilite)  %highlight current variable

      drawnow
      eemulator(['info' int2str(r)])  %update info field

   elseif strcmp(op(1,1:3),'inf')  %update EEM info fields

      h_e1 = findobj(h_dlg,'Tag','editE1');
      h_info = findobj(h_dlg,'Tag','txtInfo');

      r = str2num(op(1,5));

      eem = eems{toprow+r-1};

      h = get(h_info,'UserData');  %get info field handles

      if ~isempty(eem)

         str = [{'eem.description'} ...
               {'eem.eemtype'} ...
               {'eem.date'} ...
               {'eem.calibration'} ...
               {'eem.excitation'} ...
               {'eem.emission'} ...
               {'eem.slits'} ...
               {'eem.dilution'} ...
               {'eem.ramanwave'} ...
               {'eem.raman'}];

         for n = 1:size(h,2)
            eval(['set(h(n),''String'',' char(str{n}) ')'])
         end

      else  %empty variable

         set(h(1),'String','')
         for n = 2:size(h,2)
            set(h(n),'String','')
         end

      end

      drawnow

   elseif strcmp(op,'newvars')  %update variables list

      %get handles
      h_vars = findobj(h_dlg,'Tag','txtVars');
      h = get(h_vars,'UserData');

      for n = 1:5
         if ~isempty(eems{toprow+n-1})
            str = eems{toprow+n-1}.description;
            if isempty(str)
               str = ' ';
            end
         else
            str = ' ';
         end
         set(h(2,n),'String',str(1,:))
      end

      eemulator(['var' int2str(r)])

   elseif strcmp(op,'compact')  %condense lists

      h_lc1 = findobj(h_dlg,'Tag','txtC1');
      h_c1 = findobj(h_dlg,'Tag','editC1');
      h_slc = findobj(h_dlg,'Tag','slrC');
      const = get(h_c1,'UserData');

      I = find(~cellfun('isempty',eems));
      if length(I) < length(eems)  %empty slots
         eems(1:length(I)) = eems(I);
         eems(length(I)+1:length(eems)) = cell(length(eems)-length(I),1);
      end

      I = find(~cellfun('isempty',const));
      if length(I) < length(const)  %empty slots
         const(1:length(I)) = const(I);
         const(length(I)+1:length(const)) = cell(length(const)-length(I),1);
      end

      set(h_e1,'UserData',eems)
      set(h_le1,'UserData',1)
      set(h_slv,'Value',length(eems)-4,'UserData',1)

      set(h_c1,'UserData',const)
      set(h_lc1,'UserData',1)
      set(h_slc,'Value',length(const)-4,'UserData',1)

      eemulator('scrollc')
      eemulator('scrolle')

   elseif strcmp(op(1,1:3),'tem')  %apply equation template selections

      h_tmp = findobj(h_dlg,'Tag','popTemplate');
      h_def = findobj(h_dlg,'Tag','editTerms');
      h_eq = findobj(h_dlg,'Tag','editEquation');

      templates = get(h_tmp,'UserData');
      val = get(h_tmp,'Value');

      if strcmp(op,'template')  %apply new template selection

         set(h_def,'String',deblank(char(templates(val,2))))
         set(h_eq,'String',deblank(char(templates(val,3))))

      elseif strcmp(op,'temp_cancel')

         h = findobj('Tag','dlgNameTemp');
         if ~isempty(h)
            close(h)
         end

         figure(h_dlg)

      elseif strcmp(op,'temp_delete')  %delete current template

         h_def = findobj(h_dlg,'Tag','editTerms');
         h_eq = findobj(h_dlg,'Tag','editEquation');

         if val > 1

            %delete active template
            if val < size(templates,1)  %middle template
               templates = templates([1:val-1 val+1:size(templates,1)],:);
            else
               templates = templates(1:val-1,:);
            end

         end

         %form new template list for popup control
         templatestr = templates{1,1};
         for n = 2:size(templates,1)
            templatestr = [templatestr '|' deblank(char(templates(n,1)))];
         end

         %update popup control settings
         set(h_tmp, ...
            'String',templatestr, ...
            'UserData',templates, ...
            'Value',1)

         %reset definition and equation editboxes
         set(h_def,'String',templates{1,2})
         set(h_eq,'String',templates{1,3})

         drawnow

         confirmdlg('init','Save changes to EEMulator preferences file?', ...
            'eemulator(''pref_temp'')')

      elseif strcmp(op,'temp_name')  %create template naming dialog

         screenres = get(0,'screensize');
         bgcolor = [0.9 0.9 0.9];

         h_namedlg = figure('Name','Name Template', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[screenres(3)-480 (screenres(4)-200)./2 400 100], ...
            'Color',bgcolor, ...
            'KeyPressFcn','figure(gcf)', ...
            'MenuBar','none', ...
            'ToolBar','none', ...
            'NumberTitle','off', ...
            'Resize','off', ...
            'Tag','dlgNameTemp');

         h1 = uicontrol(h_namedlg, ...
            'Style','text', ...
            'Position',[10 66 95 18], ...
            'FontWeight','bold', ...
            'HorizontalAlignment','left', ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',bgcolor, ...
            'String','Equation Name');

         h1 = uicontrol(h_namedlg, ...
            'Style','edit', ...
            'Position',[105 64 290 22], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[1 1 1], ...
            'HorizontalAlignment','left', ...
            'Min',0, ...
            'Max',2, ...
            'String',templates{val,1}, ...
            'Tag','editName');

         h1 = uicontrol(h_namedlg, ...
            'Style','checkbox', ...
            'Position',[80 35 240 22], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',bgcolor, ...
            'Value',0, ...
            'String','Save updated list in EEMulator preference file?', ...
            'Tag','popSave');

         h1 = uicontrol(h_namedlg, ...
            'Style','pushbutton', ...
            'Position',[5 5 60 25], ...
            'String','Cancel', ...
            'TooltipString','Cancel adding template to list', ...
            'CallBack','eemulator(''temp_cancel'')');

         h1 = uicontrol(h_namedlg, ...
            'Style','pushbutton', ...
            'Position',[335 5 60 25], ...
            'String','Accept', ...
            'TooltipString','Accept entry and update templates list', ...
            'CallBack','eemulator(''temp_evalname'')');

         set(h_namedlg,'Visible','on'); drawnow

      elseif strcmp(op,'temp_evalname')

         h_namedlg = findobj('Tag','dlgNameTemp');
         h_name = findobj(h_namedlg,'Tag','editName');
         h_save = findobj(h_namedlg,'Tag','popSave');

         str = deblank(get(h_name,'String'));
         savetemp = get(h_save,'Value');

         if ~isempty(str)

            close(h_namedlg)
            figure(h_dlg)

            %get editbox fields
            h_def = findobj(h_dlg,'Tag','editTerms');
            h_eq = findobj(h_dlg,'Tag','editEquation');

            %add new template to bottom of list
            templates = [templates ; ...
                  {str(1,:)} {get(h_def,'String')} {get(h_eq,'String')}];

            %update current template pointer
            val = size(templates,1);

            %sort templates list alphabetically (leaving 'none' at top)
            [tmp,I] = sort(templates(2:size(templates,1),1));
            I = [1;I+1];
            templates = templates(I,:);

            %form new template list for popup control
            templatestr = templates{1,1};
            for n = 2:size(templates,1)
               templatestr = [templatestr '|' deblank(char(templates(n,1)))];
            end

            %update popup control settings
            set(h_tmp, ...
               'String',templatestr, ...
               'UserData',templates, ...
               'Value',find(I == val))

            drawnow

            if savetemp == 1
               eemulator('pref_temp')
            end

         else  %bad entry

            figure(h_namedlg)
            errorbox('init','Template names must be valid text strings')

         end

      end

   elseif strcmp(op(1,1:3),'con')  %update user constants array

      crow = str2num(op(1,4));

      %get editbox handles
      h_const = findobj(h_dlg,'Tag','txtConst');
      h = get(h_const,'UserData');

      entry = get(h(2,crow),'String');
      val = str2num(entry);

      %get user const array
      h_c1 = findobj(h_dlg,'Tag','editC1');
      cdata = get(h_c1,'UserData');

      %get toprow
      h_slrc = findobj(h_dlg,'Tag','slrC');
      ctop = get(h_slrc,'UserData');

      if ~isempty(val)

         %update editbox index
         h_lc1 = findobj(h_dlg,'Tag','txtC1');
         set(h_lc1,'UserData',crow)

         %update constants array
         cdata{ctop+crow-1} = val;
         set(h_c1,'UserData',cdata)

      elseif ~isempty(entry)  %bad entry

         %clear editbox
         set(h(2,crow),'String','')

         %update constants array
         cdata{ctop+crow-1} = [];
         set(h_c1,'UserData',cdata)

         errorbox('init','Entry must be a valid scalar (i.e. single number)')

      end

   elseif strcmp(op,'view')  %plot EEM data

      eem = eems{toprow+r-1};

      if ~isempty(eem)

         if strcmp(eem.eemtype(1,1:3),'Raw')
            datatype = 'Raw Scan Data (cps)';
            zlblstr = 'Fluorescence (cps)';
         elseif length(find(findstr(eem.eemtype,'&'))) > 0
            datatype = 'Dilution- & Scatter-corrected, Calibrated Data (ppb QSE)';
            zlblstr = 'Fluorescence (QSE)';
         else
            datatype = 'Scatter-corrected, Calibrated Data (ppb QSE)';
            zlblstr = 'Fluorescence (QSE)';
         end

         info = {[eem.description] ...
               [datatype] ...
               [eem.date] ...
               [eem.excitation] ...
               [eem.emission] ...
               [eem.calibration] ...
               [eem.slits] ...
               [eem.dilution]};

         if ~isempty(eem.description)
            plottitle = deblank(eem.description(1,:));
         else
            plottitle = 'EEM Plot';
         end

         eemplot('newfig',eem.data,0,plottitle,zlblstr);

         h_info = findobj(gcf,'Tag','eeminfo');
         set(h_info,'UserData',info)

      end

   elseif strcmp(op,'remove')  %clear EEM from variables list

      if ~isempty(eems{toprow+r-1})
         eems{toprow+r-1} = [];
         set(h_e1,'UserData',eems)
         eemulator('newvars')
      end

   elseif strcmp(op,'add')  %add EEM to variables list

      global EEMLOADPATH EEMSAVEPATH

      error = 0;
      cancel = 0;
      curpath = pwd;
      errormsg = '';

      if ~isempty(EEMLOADPATH)
         cd(EEMLOADPATH)
      elseif ~isempty(EEMSAVEPATH)
         cd(EEMSAVEPATH)
      end

      [fn,pn] = uigetfile('*.eem','Select Fluorescence Data File to Open');
      drawnow

      if fn ~= 0  %filename returned

         cd(pn )
         try
            load(fn,'-mat');
         catch
            error = 1;
         end
         EEMLOADPATH = pn;

         if error == 0

            if exist('eem') ~= 1

               error = 1;
               errormsg = 'No valid EEM data in the selected file';

            elseif ~isstruct(eem)

               error = 1;
               errormsg = 'No valid EEM data in the selected file';

            end

         else

            errormsg = 'Invalid Matlab data file';

         end

      else  %cancelled by user

         error = 1;

      end

      cd(curpath)

      if error == 0

         eemtypes = [{'eem.raw'} {'eem.corrected'} {'eem.blanked'}];
         str = [{'Raw Scan Data (cps)'} ...
               {'Scatter-corrected, Calibrated Data (ppb QSE)'} ...
               {'Dilution- & Scatter-corrected, Calibrated Data (ppb QSE)'}];
         eemtypestr = [{'Raw Scan Data (cps)'} ...
               {'Scatter-corrected & Calibrated (QSE)'} ...
               {'Calibrated & Dilution-corrected (QSE)'}];

         I = find([~isempty(eem.raw) ~isempty(eem.corrected) ~isempty(eem.blanked)]);

         if length(I) > 1

            h = gcf;
            figpos = get(h,'Position');

            I_sel = listdialog('Name','Select EEM variables', ...
               'ListString',str(I), ...
               'InitialValue',length(I), ...
               'PromptString','Select EEM data to add to variables list', ...
               'ListSize',[figpos(1)+70 figpos(2)+320 350 180]);

            figure(h)
            drawnow

            if isempty(I_sel)  %dialog cancelled by user
               cancel = 1;
            end

         elseif length(I) == 1

            I_sel = I;

         else  %no data in file

            cancel = 1;
            errormsg = 'No EEM data in the selected file';

         end

         if cancel == 0  %get data

            I_free = find(cellfun('isempty',eems));

            if length(I_free) >= length(I_sel)

               for n = 1:length(I_sel)

                  eval(['data = ' char(eemtypes{I(I_sel(n))}) ';'])

                  if isfield(eem,'type')
                     eemtype = eem.type;
                  else
                     eemtype = 'data';
                  end

                  if strcmp(eemtype,'data')

                     if I(I_sel(n)) > 1
                        calstr = eem.calibration;
                        dilstr = num2str(eem.df);
                     else
                        calstr = 'N/A';
                        dilstr = 'N/A';
                     end

                     if ~isfield(eem,'ramanwave')
                        eem.ramanwave = [275 303];
                     end

                     eems{I_free(n)} = struct('data',data, ...
                        'description',eem.description, ...
                        'eemtype',char(eemtypestr{I(I_sel(n))}), ...
                        'date',eem.date, ...
                        'calibration',calstr, ...
                        'excitation',[num2str(data(1,2)) '-' num2str(data(1,size(data,2))) ...
                           'nm by ' num2str(data(1,4)-data(1,3)) 'nm'], ...
                        'emission',[num2str(data(2,1)) '-' num2str(data(size(data,1),1)) ...
                           'nm by ' num2str(data(4,1)-data(3,1)) 'nm'], ...
                        'slits',[num2str(eem.slits(1)) 'nm Ex, ' num2str(eem.slits(2)) 'nm Em'], ...
                        'dilution',dilstr, ...
                        'ramanwave',[int2str(eem.ramanwave(1)) '/' int2str(eem.ramanwave(2))], ...
                        'raman',num2str(eem.raman));

                  else

                     eems{I_free(n)} = struct('data',data, ...
                        'description',eem.description, ...
                        'eemtype','Calculated EEM', ...
                        'date',eem.date, ...
                        'calibration','N/A', ...
                        'excitation',[num2str(data(1,2)) '-' num2str(data(1,size(data,2))) ...
                           'nm by ' num2str(data(1,4)-data(1,3)) 'nm'], ...
                        'emission',[num2str(data(2,1)) '-' num2str(data(size(data,1),1)) ...
                           'nm by ' num2str(data(4,1)-data(3,1)) 'nm'], ...
                        'slits','N/A', ...
                        'dilution','N/A', ...
                        'ramanwave','N/A', ...
                        'raman','N/A');

                  end

               end

               set(h_e1,'UserData',eems)

               newtoprow = max(1,I_free(n)-4);
               newrow = I_free(n) - newtoprow + 1;
               newval = get(h_slv,'Max') + 1 - newtoprow;

               set(h_slv,'Value',newval,'UserData',newtoprow)
               set(h_le1,'UserData',newrow)

               eemulator('scrolle')

            else  %not enough free slots

               messagebox('init', ...
                  str2mat('Not enough free slots to add selected variables', ...
                  '~~~','Increase maximum variables setting or remove unneeded EEMs'), ...
                  '','Error',[.8 0 0])

            end

         end

      end

      if ~isempty(errormsg)
         errorbox('init',errormsg)
      end

   elseif strcmp(op(1,1:2),'ws')  %load/save variables as workspace file

      %get user const handles
      h_c1 = findobj(h_dlg,'Tag','editC1');
      h_slrc = findobj(h_dlg,'Tag','slrC');
      h_lc1 = findobj(h_dlg,'Tag','txtC1');

      %get equation pane handles
      h_def = findobj(h_dlg,'Tag','editTerms');
      h_eq = findobj(h_dlg,'Tag','editEquation');
      h_templ = findobj(h_dlg,'Tag','popTemplate');

      %get options handle
      h_opt = findobj(h_dlg,'Tag','cmdOptions');

      global EEMLOADPATH EEMSAVEPATH
      curpath = pwd;
      errormsg = '';

      if strcmp(op,'wssave')

         ws = struct('eemvardata',{eems}, ...
            'eemvartop',toprow, ...
            'eemvarcurrent',r, ...
            'constdata',{get(h_c1,'UserData')}, ...
            'consttop',get(h_slrc,'UserData'), ...
            'constcurrent',get(h_lc1,'UserData'), ...
            'terms',get(h_def,'String'), ...
            'equation',get(h_eq,'String'), ...
            'templates',{get(h_templ,'UserData')}, ...
            'templatesel',get(h_templ,'Value'), ...
            'options',{get(h_opt,'UserData')});

         if ~isempty(EEMSAVEPATH)
            cd(EEMSAVEPATH)
         elseif ~isempty(EEMLOADPATH)
            cd(EEMLOADPATH)
         end

         [fn,pn] = uiputfile('*.ews','Select filename and location for workspace data');
         drawnow

         if fn ~= 0  %filename returned

            [pathname,filename] = fileparts(fn);
            filename = [filename '.ews'];

            cd(pn)
            save(filename,'ws')

            EEMSAVEPATH = pn;

         end

      else  %load workspace

         if ~isempty(EEMLOADPATH)
            cd(EEMLOADPATH)
         elseif ~isempty(EEMSAVEPATH)
            cd(EEMSAVEPATH)
         end

         error = 0;

         [fn,pn] = uigetfile('*.ews','Select workspace file to load');
         drawnow

         if fn ~= 0  %filename returned

            cd(pn)
            try
               load(fn,'-mat');
            catch
               error = 1;
            end
            EEMLOADPATH = pn;
            cd(curpath)

            if error == 0
               if exist('ws') ~= 1
                  error = 1;
                  errormsg = 'No valid workspace variable in the selected file';
               end
            else
               errormsg = ['''' fn ''' is not a valid Matlab data file'];
            end

            if error == 0  %valid workspace file

               set(h_e1,'UserData',ws.eemvardata)
               set(h_slv,'Value',length(ws.eemvardata)-3-ws.eemvartop, ...
                  'UserData',ws.eemvartop)
               set(h_le1,'UserData',ws.eemvarcurrent)
               set(h_c1,'UserData',ws.constdata)
               set(h_slrc,'Value',length(ws.constdata)-3-ws.consttop, ...
                  'UserData',ws.consttop)
               set(h_lc1,'UserData',ws.constcurrent)
               set(h_def,'String',ws.terms)
               set(h_eq,'String',ws.equation)
               set(h_templ,'UserData',ws.templates,'Value',ws.templatesel)
               set(h_opt,'UserData',ws.options)

               eemulator('opt_update')  %update changes in options, slider position
               eemulator('scrollc')
               eemulator('scrolle')

            end

         end

      end

      cd(curpath)

      if ~isempty(errormsg)
         errorbox('init',errormsg)
      end

   elseif strcmp(op,'reset')  %clear fields

      %get uicontrol handles
      h_vars = findobj(h_dlg,'Tag','txtVars');
      h_const = findobj(h_dlg,'Tag','txtConst');
      h_info = findobj(h_dlg,'Tag','txtInfo');
      h_def = findobj(h_dlg,'Tag','editTerms');
      h_eq = findobj(h_dlg,'Tag','editEquation');
      h_temp = findobj(h_dlg,'Tag','popTemplate');
      h_lc1 = findobj(h_dlg,'Tag','txtC1');
      h_c1 = findobj(h_dlg,'Tag','editC1');
      h_slc = findobj(h_dlg,'Tag','slrC');
      h_eval = findobj(h_dlg,'Tag','cmdEval');

      %get stored handles matrices
      varh = get(h_vars,'UserData');
      consth = get(h_const,'UserData');
      infoh = get(h_info,'UserData');

      %reset stored values
      const = get(h_c1,'UserData');
      set(h_c1,'UserData',cell(length(const),1))
      set(h_e1,'UserData',cell(length(eems),1))
      set(h_le1,'UserData',1)
      set(h_lc1,'UserData',1)
      set(h_eval,'UserData',[])

      %clear editboxes
      set(consth(2,:)',{'String'},cellstr(blanks(size(consth,2))'))
      set(varh(2,:)',[{'String'},{'BackgroundColor'}], ...
         [cellstr(blanks(size(varh,2))') repmat({[1 1 1]},size(varh,2),1)])
      set(infoh',{'String'},cellstr(blanks(length(infoh))'))
      set(h_def,'String','')
      set(h_eq,'String','')

      %reset other controls
      set(h_temp,'Value',1)
      set(h_slv,'Value',get(h_slv,'Max'),'UserData',1)
      set(h_slc,'Value',get(h_slc,'Max'),'UserData',1)

      %reset editbox labels
      set(consth(1,:)',{'String'}, ...
         cellstr([char(ones(size(consth,2),1).*'C') int2str([1:size(consth,2)]')]))
      set(varh(1,:)',{'String'}, ...
         cellstr([char(ones(size(varh,2),1).*'E') int2str([1:size(varh,2)]')]))

   elseif strcmp(op(1,1:2),'eq')  %test or evaluate expression

      %get editbox entries
      h_def = findobj(h_dlg,'Tag','editTerms');
      h_eq = findobj(h_dlg,'Tag','editEquation');

      defstr = get(h_def,'String');
      eqstr = deblank(get(h_eq,'String'));

      %initialize variables
      I_c = [];
      I_e = [];
      expr1 = ';';
      I_eems = [];
      I_const = [];
      eems_unmatch = [];
      eems_matched = [];
      ex_array = [1 2 3];
      em_array = [1 2 3 4];
      fl = [];
      fl_calc = [];
      eemcalc = [];
      error = 0;
      errormsg = '';

      warning off;  %turn off warning messages

      %clean & concatenate term definition lines
      for n = 1:size(defstr,1)
         tmp = deblank(defstr(n,:));
         if ~isempty(tmp)
            if strcmp(tmp(1),'%') ~= 1
               tmp = strtok(tmp,'%');
               if ~isempty(tmp)
                  tmp = deblank(tmp);
                  if strcmp(tmp(length(tmp)),';') ~= 1
                     expr1 = [expr1 tmp ';'];
                  else
                     expr1 = [expr1 tmp];
                  end
               end
            end
         end
      end

      %clean up equation string
      if ~isempty(eqstr)
         eqstr = strtok(eqstr,'%');
         if ~isempty(eqstr)
            eqstr = deblank(eqstr);
            if strcmp(eqstr(length(eqstr)),';') ~= 1
               eqstr = ['fl_calc = ' eqstr ';'];
            end
         end
      end

      if ~(isempty(eqstr) & isempty(expr1))  %analyze expression terms

         %get option settings for validation
         h_opt = findobj(h_dlg,'Tag','cmdOptions');
         opt = get(h_opt,'UserData');

         %concatenate expressions to form final equation expression
         expr = [expr1(2:length(expr1)) eqstr];
         symb = ['*';'/';'^'];
         for n = 1:3  %convert matrix math symbols to elementwise forms
            expr = strrep(expr,['.' symb(n)],symb(n));
            expr = strrep(expr,symb(n),['.' symb(n)]);
         end

         %get EEM rownumbers from placeholders
         I_e = findstr(expr,'E');
         if ~isempty(I_e)
            I_eems = zeros(length(I_e),1);
            for n = 1:length(I_e)
               pos = 1;
               numstr = '';
               nextchar = expr(I_e(n)+pos);
               while ~isempty(str2num(nextchar))
                  numstr = [numstr nextchar];
                  if I_e(n) < length(expr)
                     pos = pos+1;
                     nextchar = expr(I_e(n)+pos);
                  else
                     break
                  end
               end
               I_eems(n) = str2num(numstr);
            end
            nulls =  length(I_e) - length(find(I_eems));
            if  nulls > 0
               error = 1;
               str = [int2str(nulls) ' EEM variables(s) could not be assigned'];
               if ~isempty(errormsg)
                  errormsg = str2mat(errormsg,str);
               else
                  errormsg = str;
               end
            else
               oob = length(find(I_eems > opt.maxerows)) + length(find(I_eems < 1));
               if oob > 0
                  error = 1;
                  str = [int2str(oob) ' EEM variables(s) out of range'];
                  if ~isempty(errormsg)
                     errormsg = str2mat(errormsg,str);
                  else
                     errormsg = str;
                  end
               end
            end
         end

         %get user constant rownumbers from placeholders
         I_c = findstr(expr,'C');
         if ~isempty(I_c)
            I_const = zeros(length(I_c),1);
            for n = 1:length(I_c)
               pos = 1;
               numstr = '';
               nextchar = expr(I_c(n)+pos);
               while ~isempty(str2num(nextchar))
                  numstr = [numstr nextchar];
                  if I_c(n) < length(expr)
                     pos = pos+1;
                     nextchar = expr(I_c(n)+pos);
                  else
                     break
                  end
               end
               I_const(n) = str2num(numstr);
            end
            %validate index
            nulls =  length(I_c) - length(find(I_const));
            if  nulls > 0
               error = 1;
               str = [int2str(nulls) ' user constants(s) could not be assigned'];
               if ~isempty(errormsg)
                  errormsg = str2mat(errormsg,str);
               else
                  errormsg = str;
               end
            else
               oob = length(find(I_const > opt.maxcrows)) + length(find(I_const < 1));
               if oob > 0
                  error = 1;
                  str = [int2str(oob) ' user constants(s) out of range'];
                  if ~isempty(errormsg)
                     errormsg = str2mat(errormsg,str);
                  else
                     errormsg = str;
                  end
               end
            end
         end

         if error == 0  %make user constant assignments

            if strcmp(op,'eqeval')  %fully evaluate expression

               %get stored user constant array
               h_c1 = findobj(h_dlg,'Tag','editC1');
               const = get(h_c1,'UserData');
               carray = const(I_const);

               for n = 1:length(I_const)
                  if ~isempty(carray{n})
                     eval(['C' int2str(I_const(n)) ' = carray{n};'],['error = 1; ' ...
                           'errormsg = ''An error occurred during user constant assignment'';'])
                  else
                     error = 1;
                     errormsg = 'Blank user constant fields cannot be used in expressions';
                     break
                  end
               end

               if error == 0  %make EEM variable assignments
                  eems_unmatched = cell(length(I_eems),1);  %initialize cell array
                  for n = 1:length(I_eems)
                     eem = eems{I_eems(n)};
                     if ~isempty(eem)
                        eems_unmatched{n} = eem.data;
                     else
                        error = 1;
                        errormsg = 'Blank EEM variables cannot be used in expressions';
                        break
                     end
                  end
                  if error == 0
                     if length(I_eems) > 1
                        eems_matched = matcheems(eems_unmatched,opt.matchopt);
                     else
                        eems_matched = eems_unmatched;
                     end
                     for n = 1:length(I_eems)
                        [ex_array,em_array,fl] = unwrapeem(eems_matched{n});
                        eval(['E' int2str(I_eems(n)) ' = fl;'], ...
                           ['error = 1; errormsg = ''An error occurred during EEM ' ...
                              'variable assignment'';'])
                     end
                  end
               end

            else  %assign ones and arrays of ones to variables for syntax check

               for n = 1:length(I_const)
                  eval(['C' int2str(I_const(n)) ' = 1;'],['error = 1; ' ...
                        'errormsg = ''An error occurred during user constant assignment'';'])
               end
               for n = 1:length(I_eems)
                  eval(['E' int2str(I_eems(n)) ' = ones(50,40);'],['error = 1; ' ...
                        'errormsg = ''An error occurred during EEM variable assignment'';'])
               end

            end

         end

         if error == 0  %evaluate expression

            eval(expr,['error = 1; ' ...
                  'errormsg = ''Equation could not be evaluated - check syntax'';'])

            if error == 0
               eval('eem_calc = wrapeem(ex_array,em_array,fl_calc);', ...
                  'error = 1; errormsg = ''Invalid EEM returned from equation'';')
            end

            if error == 0

               if strcmp(op,'eqeval')

                  if ~isempty(eem_calc)  %check for null matrix

                     %get calculation type
                     h_temp = findobj(h_dlg,'Tag','popTemplate');
                     templates = get(h_temp,'UserData');
                     val = get(h_temp,'Value');
                     expr = strrep(expr,'fl_calc =','EEM_calculated =');
                     if val > 1
                        tempstr = templates{val,1};
                     else
                        tempstr = 'User-defined calculation';
                     end

                     eem = struct('type','calc', ...
                        'description',str2mat(tempstr,expr), ...
                        'date',datestr(now), ...
                        'calibration',[], ...
                        'scatterpeaks',[], ...
                        'scattertol',[], ...
                        'ramanwave',[], ...
                        'raman',[], ...
                        'slits',[], ...
                        'qsparms',[], ...
                        'raw',eem_calc, ...
                        'corrected',[], ...
                        'blanked',[], ...
                        'diluent',[], ...
                        'df',[]);

                     h_eval = findobj(h_dlg,'Tag','cmdEval');
                     set(h_eval,'UserData',eem)

                     eemulator('eemname')

                  else  %null EEM
                     messagebox('init','Equation did not produce valid EEM data', ...
                        '','Error',[.8 0 0])
                  end

               else  %report test
                  messagebox('init','Expressions passed syntax test', ...
                     '','Test Result',[0 0 .8])
               end

            end

         end

         if error == 1  %create error message

            messagebox('init',errormsg,'','Error',[.8 0 0])

         end

      else  %no valid expression

         errorbox('init','Equation is blank or invalid')

      end

   elseif strcmp(op(1,1:3),'eem')  %handle naming, saving of calculated EEMs

      %get stored EEM variable
      h_eval = findobj(h_dlg,'Tag','cmdEval');
      eem = get(h_eval,'UserData');

      if strcmp(op,'eemname')  %open name editing dialog

         h_namedlg = findobj('Tag','dlgNameEEM');
         if ~isempty(h_namedlg)
            close(h_namedlg)
         end

         screenres = get(0,'screensize');

         h_namedlg = figure('Name','EEM Description', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[screenres(3)-480 (screenres(4)-200)./2 400 200], ...
            'Color',[0.88 0.88 0.88], ...
            'KeyPressFcn','eemulator(''eemsave'')', ...
            'MenuBar','none', ...
            'ToolBar','none', ...
            'NumberTitle','off', ...
            'Resize','off', ...
            'Tag','dlgNameEEM');

         h1 = uicontrol(h_namedlg, ...
            'Style','text', ...
            'Position',[5 175 390 18], ...
            'FontWeight','bold', ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'String','Edit EEM Description (first line will be default plot title)');

         h1 = uicontrol(h_namedlg, ...
            'Style','edit', ...
            'Position',[5 40 390 134], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[1 1 1], ...
            'HorizontalAlignment','left', ...
            'Min',0, ...
            'Max',2, ...
            'String',eem.description, ...
            'Tag','editName');

         h1 = uicontrol(h_namedlg, ...
            'Style','pushbutton', ...
            'Position',[120 5 60 25], ...
            'String','Cancel', ...
            'TooltipString','Cancel saving of calculated EEM file', ...
            'CallBack','eemulator(''eemnamecancel'')');

         h1 = uicontrol(h_namedlg, ...
            'Style','pushbutton', ...
            'Position',[220 5 60 25], ...
            'String','Accept', ...
            'TooltipString','Accept changes and proceed to save EEM', ...
            'CallBack','eemulator(''eemsave'')');

         set(h_namedlg,'Visible','on'); drawnow

      elseif strcmp(op,'eemnamecancel')  %evaluate name dialog cancel click

         h_namedlg = findobj('Tag','dlgNameEEM');

         close(h_namedlg)
         figure(h_dlg)
         drawnow

         eemulator('eemplot')

      elseif strcmp(op,'eemsave')

         h_namedlg = findobj('Tag','dlgNameEEM');
         h_edit = findobj(h_namedlg,'Tag','editName');

         error = 0;
         eval('str = get(h_edit,''String'');','error = 1;')

         if error == 1  %bad editbox entry

            figure(h_namedlg)
            errorbox('init','Name entry is invalid')

         else

            close(h_namedlg)
            figure(h_dlg)
            drawnow

            eem.description = str;
            set(h_eval,'UserData',eem)

            curpath = pwd;
            global EEMSAVEPATH EEMLOADPATH
            if ~isempty(EEMSAVEPATH)
               cd(EEMSAVEPATH)
            elseif ~isempty(EEMLOADPATH)
               cd(EEMLOADPATH)
            end

            [fn,pn] = uiputfile('*.eem','Select filename and location for calculated EEM');
            drawnow

            if fn ~= 0

               [tmp,fn] = fileparts(fn);
               cd(pn)
               save([fn '.eem'],'eem')
               EEMSAVEPATH = pn;

            end

            cd(curpath)

            eemulator('eemplot')

         end

      elseif strcmp(op,'eemplot')

         h_opt = findobj(h_dlg,'Tag','cmdOptions');
         opt = get(h_opt,'UserData');

         if opt.autoadd == 1  %add eem to var list

            I_free = find(cellfun('isempty',eems));

            if ~isempty(I_free)

               eems{I_free(1)} = struct('data',eem.raw, ...
                  'description',eem.description, ...
                  'eemtype','Calculated EEM', ...
                  'date',eem.date, ...
                  'calibration','N/A', ...
                  'excitation',[num2str(eem.raw(1,2)) '-' num2str(eem.raw(1,size(eem.raw,2))) ...
                  'nm by ' num2str(eem.raw(1,4)-eem.raw(1,3)) 'nm'], ...
                  'emission',[num2str(eem.raw(2,1)) '-' num2str(eem.raw(size(eem.raw,1),1)) ...
                     'nm by ' num2str(eem.raw(4,1)-eem.raw(3,1)) 'nm'], ...
                  'slits','N/A', ...
                  'dilution','N/A', ...
                  'ramanwave','N/A', ...
                  'raman','N/A');

               set(h_e1,'UserData',eems)

               newtoprow = max(1,I_free(1)-4);
               newrow = I_free(1) - newtoprow + 1;
               newval = get(h_slv,'Max') + 1 - newtoprow;

               set(h_slv,'Value',newval,'UserData',newtoprow)
               set(h_le1,'UserData',newrow)

               eemulator('scrolle')

            else  %no slots

               messagebox('init', ...
                  str2mat('Not enough free slots to add the calculated EEM to the list', ...
                  '~~~','Increase maximum variables setting or remove unneeded EEMs'), ...
                  '','Error',[.8 0 0])

            end

         end

         if opt.autoplot == 1  %plot eem
            dataplot('surfnewfig',eem);
         end

         %clear stored eem
         set(h_eval,'UserData',[])

      end

   elseif strcmp(op(1,1:3),'opt')

      h_opt = findobj(h_dlg,'Tag','cmdOptions');
      options = get(h_opt,'UserData');

      if strcmp(op,'opt_update')

         %update highlight color
         h_vars = findobj(h_dlg,'Tag','txtVars');
         h = get(h_vars,'UserData');
         set(h(2,r),'BackgroundColor',options.hilite)

         %update storage matrices
         if options.maxerows ~= size(eems,1)
            if options.maxerows < size(eems,1)
               eems = eems(1:options.maxerows,1);
            else
               eems = [eems ; cell(options.maxerows-size(eems,1),1)];
            end
            set(h_e1,'UserData',eems)
         end

         h_c1 = findobj(h_dlg,'Tag','editC1');
         const = get(h_c1,'UserData');
         if options.maxcrows ~= size(const,1)
            if options.maxcrows < size(const,1)
               const = const(1:options.maxcrows,1);
            else
               const = [const ; cell(options.maxcrows-size(const,1),1)];
            end
            set(h_c1,'UserData',const)
         end

         %update sliders
         h_slc = findobj(h_dlg,'Tag','slrC');
         if get(h_slc,'Max') ~= (options.maxcrows-4);
            h_lc1 = findobj(h_dlg,'Tag','txtC1');
            set(h_lc1,'UserData',1)
            set(h_slc,'Max',max(1,options.maxcrows-4), ...
               'SliderStep',[1./max(1,(options.maxcrows-5)) 5./max(1,(options.maxcrows-5))], ...
               'Value',max(1,options.maxcrows-4), ...
               'UserData',1)
            eemulator('scrollc')
         end
         if get(h_slv,'Max') ~= (options.maxerows-4);
            set(h_le1,'UserData',1)
            set(h_slv,'Max',max(1,options.maxerows-4), ...
               'SliderStep',[1./max(1,(options.maxerows-5)) 5./max(1,(options.maxerows-5))], ...
               'Value',max(1,options.maxerows-4), ...
               'UserData',1);
            eemulator('scrolle')
         end

         drawnow

      elseif strcmp(op,'options')  %create options editing dialog

         h_optdlg = findobj('Tag','dlgOptions');
         if ~isempty(h_optdlg)
            close(h_optdlg)
         end

         screenres = get(0,'screensize');

         h_optdlg = figure('Name','Options', ...
            'Renderer','zbuffer', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[screenres(3)-480 (screenres(4)-200)./2 400 270], ...
            'Color',[0.88 0.88 0.88], ...
            'KeyPressFcn','figure(gcf)', ...
            'MenuBar','none', ...
            'ToolBar','none', ...
            'NumberTitle','off', ...
            'Resize','off', ...
            'Tag','dlgOptions');

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[5 240 390 18], ...
            'FontWeight','bold', ...
            'ForegroundColor',[.8 0 0], ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'String','Edit EEMulator Program Options');

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[15 210 130 18], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'String','Maximum EEM Variables');

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[15 180 130 18], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'String','Maximum User Constants');

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[15 150 130 18], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'String','Active EEM Highlight');

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[15 120 130 18], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'String','Matrix Matching');

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[15 90 130 18], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'String','Calculated EEM Options');

         h1 = uicontrol(h_optdlg, ...
            'Style','edit', ...
            'Position',[150 209 60 20], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[1 1 1], ...
            'HorizontalAlignment','left', ...
            'Tag','editMaxerows', ...
            'String',int2str(options.maxerows));

         h1 = uicontrol(h_optdlg, ...
            'Style','edit', ...
            'Position',[150 179 60 20], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[1 1 1], ...
            'HorizontalAlignment','left', ...
            'Tag','editMaxcrows', ...
            'String',int2str(options.maxcrows));

         h1 = uicontrol(h_optdlg, ...
            'Style','text', ...
            'Position',[150 150 50 18], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',options.hilite, ...
            'String','', ...
            'Tag','txtHilite');

         h1 = uicontrol(h_optdlg, ...
            'Style','pushbutton', ...
            'Position',[205 148 60 22], ...
            'String','Pick Color', ...
            'Callback','eemulator(''opt_color'')');

         h1 = uicontrol(h_optdlg, ...
            'Style','popup', ...
            'Position',[150 118 220 22], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[1 1 1], ...
            'HorizontalAlignment','left', ...
            'Value',options.matchopt+1, ...
            'Tag','popMatchopt', ...
            'String','Subsample Higher-density Matrix|Interpolate Lower-density Matrix');

         h1 = uicontrol(h_optdlg, ...
            'Style','checkbox', ...
            'Position',[150 90 115 18], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'Tag','chkPlot', ...
            'Value',options.autoplot, ...
            'String','Plot Automatically');

         h1 = uicontrol(h_optdlg, ...
            'Style','checkbox', ...
            'Position',[280 90 115 18], ...
            'ForegroundColor',[0 0 0], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'Tag','chkAdd', ...
            'Value',options.autoadd, ...
            'String','Add to EEM List');

         h1 = uicontrol(h_optdlg, ...
            'Style','checkbox', ...
            'Position',[65 50 260 18], ...
            'ForegroundColor',[0 0 .8], ...
            'BackgroundColor',[0.9 0.9 0.9], ...
            'HorizontalAlignment','left', ...
            'Tag','chkSave', ...
            'Value',0, ...
            'String','Save options settings in EEMulator preference file?');

         h1 = uicontrol(h_optdlg, ...
            'Style','pushbutton', ...
            'Position',[10 5 60 25], ...
            'String','Cancel', ...
            'TooltipString','Cancel changes and close dialog', ...
            'CallBack','eemulator(''opt_cancel'')');

         h1 = uicontrol(h_optdlg, ...
            'Style','pushbutton', ...
            'Position',[170 5 60 25], ...
            'String','Defaults', ...
            'TooltipString','Restore all fields to default values', ...
            'CallBack','eemulator(''opt_default'')');

         h1 = uicontrol(h_optdlg, ...
            'Style','pushbutton', ...
            'Position',[330 5 60 25], ...
            'String','Accept', ...
            'TooltipString','Accept changes and return to EEMulator', ...
            'CallBack','eemulator(''opt_eval'')');

         set(h_optdlg,'Visible','on'); drawnow

      else

         h_optdlg = findobj('Tag','dlgOptions');
         h_maxerows = findobj(h_optdlg,'Tag','editMaxerows');
         h_maxcrows = findobj(h_optdlg,'Tag','editMaxcrows');
         h_hilite = findobj(h_optdlg,'Tag','txtHilite');
         h_matchopt = findobj(h_optdlg,'Tag','popMatchopt');
         h_plot = findobj(h_optdlg,'Tag','chkPlot');
         h_add = findobj(h_optdlg,'Tag','chkAdd');
         h_save = findobj(h_optdlg,'Tag','chkSave');

         if strcmp(op,'opt_cancel')  %cancel options dialog

            close(h_optdlg)
            figure(h_dlg)
            drawnow

         elseif strcmp(op,'opt_color')  %color callback

            c = uisetcolor(get(h_hilite,'BackgroundColor'));

            drawnow

            set(h_hilite,'BackgroundColor',c)

         elseif strcmp(op,'opt_default')  %set defaults

            if exist('eemulator.mat') == 2
               load eemulator.mat
            else
               options = struct('maxerows',25, ...
                  'maxcrows',25', ...
                  'hilite',[1 1 0.5], ...
                  'matchopt',1, ...
                  'autoplot',1, ...
                  'autoadd',1);
            end

            set(h_maxerows,'String',num2str(options.maxerows))
            set(h_maxcrows,'String',num2str(options.maxcrows))
            set(h_hilite,'BackgroundColor',options.hilite)
            set(h_matchopt,'Value',options.matchopt+1)
            set(h_plot,'Value',options.autoplot)
            set(h_add,'Value',options.autoadd)
            set(h_save,'Value',0)

            drawnow

         elseif strcmp(op,'opt_eval')  %evaluate options

            maxerows = str2num(get(h_maxerows,'String'));
            maxcrows = str2num(get(h_maxcrows,'String'));
            hilite = get(h_hilite,'BackgroundColor');
            matchopt = get(h_matchopt,'Value')-1;
            autoplot = get(h_plot,'Value');
            autoadd = get(h_add,'Value');
            saveopt = get(h_save,'Value');

            error = 0;

            %validate maxerows
            if maxerows <= 5
               error = 1;
               errorbox('init','Maximum EEM Variables setting must be > 5')
            else
               I_eems = find(~cellfun('isempty',eems));
               if ~isempty(I_eems)
                  if maxerows < I_eems(length(I_eems))
                     error = 1;
                     errorbox('init',['Maximum EEM Variables setting lower than ' ...
                           'existing rows'])
                  end
               end
            end

            %validate maxcrows
            if error == 0
               if maxcrows <= 5
                  error = 1;
                  errorbox('init','Maximum User Constants setting must be > 5')
               else
                  h_c1 = findobj(h_dlg,'Tag','editC1');
                  const = get(h_c1,'UserData');
                  I_const = find(~cellfun('isempty',const));
                  if ~isempty(I_const)
                     if maxcrows < I_const(length(I_const))
                        error = 1;
                        errorbox('init',['Maximum User Constants setting lower than ' ...
                              'existing rows'])
                     end
                  end
               end
            end

            if error == 0  %update stored options

               close(h_optdlg)
               figure(h_dlg)
               drawnow

               options = struct('maxerows',maxerows, ...
                  'maxcrows',maxcrows', ...
                  'hilite',hilite, ...
                  'matchopt',matchopt, ...
                  'autoplot',autoplot, ...
                  'autoadd',autoadd);

               set(h_opt,'UserData',options)

               eemulator('opt_update')  %update program options

               if saveopt == 1  %save changes in preference file
                  eemulator('pref_opt')
               end

            end

         end

      end

   elseif strcmp(op(1,1:3),'pre')  %update store preferences to EEMTOOLSPATH

      cancel = 0;

      if strcmp(op,'pref_temp')  %get stored templates
         h_temp = findobj(h_dlg,'Tag','popTemplate');
         newtemp = get(h_temp,'UserData');
      elseif strcmp(op,'pref_opt')  %get stored options
         h_opt = findobj(h_dlg,'Tag','cmdOptions');
         newopt = get(h_opt,'UserData');
      else
         cancel = 1;
      end

      if cancel == 0

         error = 0;
         curpath = pwd;

         global EEMTOOLSPATH
         if ~isempty(EEMTOOLSPATH)
            cd(EEMTOOLSPATH)
         end

         try
            load('eemulator.mat');
         catch
            error = 1;
         end

         if error == 0

            if strcmp(op,'pref_temp')
               templates = newtemp;
            else
               options = newopt;
            end

            save eemulator templates options

         else  %can't locate pref file - prompt for name

            [fn,pn] = uigetfile('eemulator.mat','Locate EEMulator Preference File');

            if fn ~= 0

               cd(pn)
               if exist('eemulator.mat') == 2
                  load eemulator.mat
               end

               if exist('templates') == 1

                  if strcmp(op,'pref_temp')
                     templates = newtemp;
                  else
                     options = newopt;
                  end

                  save eemulator templates options

               else  %bad pref file

                  errorbox('init','Invalid preference file - preferences not saved')

               end

            end

         end

         cd(curpath)

      end

   end

end