function figcolors(op)
%Dialog box for setting EEMplot figure colors
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 6/12/2004

if nargin == 0  %create dialog

   h_fig = gcf;

   h_t = get(gca,'title');
   h_bar = findobj(h_fig,'Tag','Colorbar');
   if ~isempty(h_bar)
      cbarclr = get(h_bar,'XColor');
   else
      cbarclr = get(gca,'ZColor');
   end

   vals = struct('figclr',get(h_fig,'Color'), ...
      'axisclr',get(gca,'Color'), ...
      'uniclr',[], ...
      'titleclr',get(h_t,'Color'), ...
      'xclr',get(gca,'xcolor'), ...
      'yclr',get(gca,'ycolor'), ...
      'zclr',get(gca,'zcolor'), ...
      'cbarclr',cbarclr);

   cmat = [vals.titleclr ; vals.xclr ; vals.yclr ; vals.zclr ; vals.cbarclr];

   if length(find(diff(cmat)~=0)) == 0  %check for color differences
      vals.uniclr = vals.titleclr;
   end

   if length(vals.uniclr) == 3
      uniformval = 1;
      textvis = 'off';
      univis = 'on';
      textclr = [.6 .6 .6];
      uniclr = vals.uniclr;
   else
      uniformval = 0;
      univis = 'off';
      textvis = 'on';
      textclr = [0 0 0];
      uniclr = vals.xclr;
   end

   bgcolor = [.9 .9 .9];
   framecolor = [.85 .85 .85];

   h_dlg = figure('Name','Figure Colors', ...
      'Visible','off', ...
      'Units','pixels', ...
      'Position',[240 280 270 287], ...
      'KeyPressFcn','figure(gcf)', ...
      'MenuBar','none', ...
      'NumberTitle','off', ...
      'Color',bgcolor, ...
      'Tag','dlgFigColor', ...
      'ToolBar','none', ...
      'Resize','off');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[.8 .8 .8], ...
      'ForegroundColor',[.9 0 0], ...
      'FontSize',9, ...
      'FontWeight','bold', ...
      'Position',[5 261 262 18], ...
      'String','Select Colors for Figure Elements', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[21 230 120 16], ...
      'String','Figure Background', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[21 205 120 16], ...
      'String','Plot Axis Background', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'Position',[21 180 150 18], ...
      'String','Uniform Plot Colors', ...
      'Style','checkbox', ...
      'Tag','chkUniform', ...
      'TooltipString','Check box to use single color for all plot text and lines', ...
      'Callback','figcolors(''uniform'')', ...
      'Value',uniformval);

   h1 = uicontrol('Parent',h_dlg, ...
      'Style','text', ...
      'Position',[5 40 260 130], ...
      'BackgroundColor',framecolor);

   h_lblT = uicontrol('Parent',h_dlg, ...
      'ForegroundColor',textclr, ...
      'BackgroundColor',framecolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[28 145 120 16], ...
      'String','Title Text', ...
      'Tag','lblTitle', ...
      'Style','text');

   h_lblX = uicontrol('Parent',h_dlg, ...
      'ForegroundColor',textclr, ...
      'BackgroundColor',framecolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[28 120 120 16], ...
      'String','X-axis Text and Lines', ...
      'Tag','lblXColor', ...
      'Style','text');

   h_lblY = uicontrol('Parent',h_dlg, ...
      'ForegroundColor',textclr, ...
      'BackgroundColor',framecolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[28 95 120 16], ...
      'String','Y-axis Text and Lines', ...
      'Tag','lblYColor', ...
      'Style','text');

   h_lblZ = uicontrol('Parent',h_dlg, ...
      'ForegroundColor',textclr, ...
      'BackgroundColor',framecolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[28 70 120 16], ...
      'String','Z-axis Text and Lines', ...
      'Tag','lblZColor', ...
      'Style','text');

   h_lblC = uicontrol('Parent',h_dlg, ...
      'ForegroundColor',textclr, ...
      'BackgroundColor',framecolor, ...
      'FontSize',9, ...
      'HorizontalAlignment','left', ...
      'Position',[28 45 120 16], ...
      'String','Colorbar Text and Lines', ...
      'Tag','lblColorbar', ...
      'Style','text');

   h_txt = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.figclr, ...
      'Position',[215 230 35 20], ...
      'Style','text', ...
      'Tag','txtFigColor');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[160 230 45 20], ...
      'String','Color', ...
      'Tag','cmdFigColor', ...
      'UserData',h_txt, ...
      'Callback','figcolors(''color'')');

   h_txt = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.axisclr, ...
      'Position',[215 205 35 20], ...
      'Style','text', ...
      'Tag','txtAxisColor');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[160 205 45 20], ...
      'String','Color', ...
      'Tag','cmdAxisColor', ...
      'UserData',h_txt, ...
      'Callback','figcolors(''color'')');

   h_txt = uicontrol('Parent',h_dlg, ...
      'Visible',univis, ...
      'BackgroundColor',uniclr, ...
      'Position',[215 180 35 20], ...
      'Style','text', ...
      'Tag','txtUniform');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[160 180 45 20], ...
      'Enable',univis, ...
      'String','Color', ...
      'Tag','cmdUniform', ...
      'UserData',h_txt, ...
      'Callback','figcolors(''color'')');

   h_txtT = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.titleclr, ...
      'Position',[215 145 35 20], ...
      'Style','text', ...
      'Tag','txtTitle', ...
      'Visible',textvis);

   h_cmdT = uicontrol('Parent',h_dlg, ...
      'Enable',textvis, ...
      'Position',[160 145 45 20], ...
      'String','Color', ...
      'Tag','cmdTitle', ...
      'UserData',h_txtT, ...
      'Callback','figcolors(''color'')');

   h_txtX = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.xclr, ...
      'Position',[215 120 35 20], ...
      'Style','text', ...
      'Tag','txtXColor', ...
      'Visible',textvis);

   h_cmdX = uicontrol('Parent',h_dlg, ...
      'Enable',textvis, ...
      'Position',[160 120 45 20], ...
      'String','Color', ...
      'Tag','cmdXColor', ...
      'UserData',h_txtX, ...
      'Callback','figcolors(''color'')');

   h_txtY = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.yclr, ...
      'Position',[215 95 35 20], ...
      'Style','text', ...
      'Tag','txtYColor', ...
      'Visible',textvis);

   h_cmdY = uicontrol('Parent',h_dlg, ...
      'Enable',textvis, ...
      'Position',[160 95 45 20], ...
      'String','Color', ...
      'Tag','cmdYColor', ...
      'UserData',h_txtY, ...
      'Callback','figcolors(''color'')');

   h_txtZ = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.zclr, ...
      'Position',[215 70 35 20], ...
      'Style','text', ...
      'Tag','txtZColor', ...
      'Visible',textvis);

   h_cmdZ = uicontrol('Parent',h_dlg, ...
      'Enable',textvis, ...
      'Position',[160 70 45 20], ...
      'String','Color', ...
      'Tag','cmdZColor', ...
      'UserData',h_txtZ, ...
      'Callback','figcolors(''color'')');

   h_txtC = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',vals.cbarclr, ...
      'Position',[215 45 35 20], ...
      'Style','text', ...
      'Tag','txtColorbar', ...
      'Visible',textvis);

   h_cmdC = uicontrol('Parent',h_dlg, ...
      'Enable',textvis, ...
      'Position',[160 45 45 20], ...
      'String','Color', ...
      'Tag','cmdColorbar', ...
      'UserData',h_txtC, ...
      'Callback','figcolors(''color'')');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[5 5 50 25], ...
      'String','Cancel', ...
      'Tag','cmdCancel', ...
      'TooltipString','Close dialog box and discard changes', ...
      'Callback','figcolors(''cancel'')');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[110 5 50 25], ...
      'String','Default', ...
      'Tag','cmdDefault', ...
      'UserData',vals, ...
      'TooltipString','Reset selections to default values', ...
      'Callback','figcolors(''default'')');

   h1 = uicontrol('Parent',h_dlg, ...
      'Position',[215 5 50 25], ...
      'String','Accept', ...
      'Tag','cmdAccept', ...
      'TooltipString','Close dialog box and apply color selections', ...
      'Callback','figcolors(''eval'')');

   lbls = [h_lblT ; h_lblX ; h_lblY ; h_lblZ ; h_lblC];
   btns = [h_cmdT ; h_cmdX ; h_cmdY ; h_cmdZ ; h_cmdC];
   cbox = [h_txtT ; h_txtX ; h_txtY ; h_txtZ ; h_txtC];

   set(h_dlg,'UserData',[{h_fig},{lbls},{btns},{cbox}],'Visible','on')
   drawnow

else  %handle callbacks

   h_dlg = findobj('Tag','dlgFigColor');
   data = get(h_dlg,'UserData');

   if strcmp(op,'color')

      h = gcbo;
      h_box = get(h,'UserData');

      c = uisetcolor(get(h_box,'BackgroundColor'));

      if length(c) == 3
         set(h_box,'BackgroundColor',c)
         drawnow
      end

   elseif strcmp(op,'uniform')

      h_chk = findobj(h_dlg,'Tag','chkUniform');
      unival = get(h_chk,'Value');

      h_unibtn = findobj(h_dlg,'Tag','cmdUniform');
      h_unicbox = findobj(h_dlg,'Tag','txtUniform');

      lbls = data{2};
      btns = data{3};
      cbox = data{4};

      if unival == 0
         set(h_unibtn,'Enable','off')
         set(h_unicbox,'Visible','off')
         set(lbls,'ForegroundColor',[0 0 0])
         set(btns,'Enable','on')
         set(cbox,'Visible','on')
      else
         set(h_unibtn,'Enable','on')
         set(h_unicbox,'Visible','on')
         set(lbls,'ForegroundColor',[.6 .6 .6])
         set(btns,'Enable','off')
         set(cbox,'Visible','off')
      end

      drawnow

   elseif strcmp(op,'cancel')

      h_fig = data{1};

      close(h_dlg)

      if ~isempty(h_fig)
         figure(h_fig)
      end

   elseif strcmp(op,'default')

      %get handles
      h_figclr = findobj(h_dlg,'Tag','txtFigColor');
      h_axclr = findobj(h_dlg,'Tag','txtAxisColor');
      h_unichk = findobj(h_dlg,'Tag','chkUniform');
      h_unibtn = findobj(h_dlg,'Tag','cmdUniform');
      h_unicbox = findobj(h_dlg,'Tag','txtUniform');
      lbls = data{2};
      btns = data{3};
      cbox = data{4};

      %apply color defaults
      set(h_figclr,'BackgroundColor',[1 1 1])
      set(h_axclr,'BackgroundColor',[.9 .9 .9])
      set(cbox(1),'BackgroundColor',[0 0 0])
      set(cbox(2),'BackgroundColor',[0 0 0])
      set(cbox(3),'BackgroundColor',[0 0 0])
      set(cbox(4),'BackgroundColor',[0 0 0])
      set(cbox(5),'BackgroundColor',[0 0 0])

      %set control properties
      set(h_unichk,'Value',1)
      set(h_unibtn,'Enable','on')
      set(h_unicbox,'BackgroundColor',[0 0 0],'Visible','on')
      set(cbox,'Visible','off')
      set(lbls,'ForegroundColor',[.6 .6 .6])
      set(btns,'Enable','off')

      drawnow

   elseif strcmp(op,'eval')

      h_def = findobj(h_dlg,'Tag','cmdDefault');
      vals = get(h_def,'UserData');

      h_figclr = findobj(h_dlg,'Tag','txtFigColor');
      h_axisclr = findobj(h_dlg,'Tag','txtAxisColor');
      h_unichk = findobj(h_dlg,'Tag','chkUniform');
      h_unicbox = findobj(h_dlg,'Tag','txtUniform');
      cbox = data{4};

      vals.figclr = get(h_figclr,'BackgroundColor');
      vals.axisclr = get(h_axisclr,'BackgroundColor');

      if get(h_unichk,'Value') == 1
         c = get(h_unicbox,'BackgroundColor');
         vals.uniclr = c;
         vals.titleclr = c;
         vals.xclr = c;
         vals.yclr = c;
         vals.zclr = c;
         vals.cbarclr = c;
      else
         vals.uniclr = [];
         vals.titleclr = get(cbox(1),'BackgroundColor');
         vals.xclr = get(cbox(2),'BackgroundColor');
         vals.yclr = get(cbox(3),'BackgroundColor');
         vals.zclr = get(cbox(4),'BackgroundColor');
         vals.cbarclr = get(cbox(5),'BackgroundColor');
      end

      h_fig = data{1};

      close(h_dlg)

      figure(h_fig)

      drawnow

      h_cbar = findobj(h_fig,'Tag','Colorbar');

      if ~isempty(h_cbar)  %deal with colorbar first to get plot handle

         h_ax = findobj(h_fig,'Type','axes');
         if h_ax(1) ~= h_cbar
            h_plot = h_ax(1);
         else
            h_plot = h_ax(2);
         end

         set(h_cbar, ...
            'XColor',vals.cbarclr, ...
            'YColor',vals.cbarclr, ...
            'ZColor',vals.cbarclr)

         set(get(h_cbar,'YLabel'),'Color',vals.cbarclr)

      else

         h_plot = gca;

      end

      set(h_fig,'Color',vals.figclr)

      h_t = get(h_plot,'Title');
      set(h_t,'Color',vals.titleclr)

      set(h_plot, ...
         'Color',vals.axisclr, ...
         'XColor',vals.xclr, ...
         'YColor',vals.yclr, ...
         'ZColor',vals.zclr)

      set(get(h_plot,'XLabel'),'Color',vals.xclr)
      set(get(h_plot,'YLabel'),'Color',vals.yclr)
      set(get(h_plot,'ZLabel'),'Color',vals.zclr)

      drawnow

   end

end
