function newaxisdlg(op)
%Axis limits dialog box
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 6/27/2000

if nargin == 0

   %clear prior instances of dialog
   h_dlg = findobj('Tag','newaxisdlg');
   if ~isempty(h_dlg)
      close(h_dlg)
   end

   h = gcf;
   h_ax = gca;

   if strcmp(get(h,'Tag'),'eemplotfig')
      plottype = '3d';
      zvis = 'on';
      checkvis = 'on';
   else
      plottype = '2d';
      checkvis = 'off';
      zvis = 'off';
   end

   %get x axis settings
   h_xlbl = get(h_ax,'XLabel');
   xlblstr = get(h_xlbl,'String');

   xlims = get(h_ax,'XLim');
   xtick = get(h_ax,'XTick');

   if length(xtick) < 2
      xtick = xlims;
   end

   if strcmp(get(h_ax,'XDir'),'normal')
      xdir = 0;
   else
      xdir = 1;
   end

   %get y axis settings
   h_ylbl = get(h_ax,'YLabel');
   ylblstr = get(h_ylbl,'String');

   ylims = get(h_ax,'YLim');
   ytick = get(h_ax,'YTick');

   if length(ytick) < 2
      ytick = ylims;
   end

   if strcmp(get(h_ax,'YDir'),'normal')
      ydir = 0;
   else
      ydir = 1;
   end

   %get z axis settings if 3d plot
   if strcmp(plottype,'3d')

      h_zlbl = get(h_ax,'ZLabel');
      zlblstr = get(h_zlbl,'String');

      zlims = get(h_ax,'ZLim');
      ztick = get(h_ax,'ZTick');

      if length(ztick) < 2
         ztick = zlims;
      end

      if strcmp(get(h_ax,'ZDir'),'normal')
         zdir = 0;
      else
         zdir = 1;
      end

      htval = 30;

   else  %2d

      zlblstr = '';
      zlims = [0 0];
      ztick = [0 0];
      zdir = 0;
      htval = 0;

   end

   h_axlims = findobj(h,'Tag','axlims');

   axlims = [xlims xtick(1) xtick(2)-xtick(1) ...
      ylims ytick(1) ytick(2)-ytick(1) ...
      zlims ztick(1) ztick(2)-ztick(1)];

   if ~isempty(h_axlims)
      origaxlims = get(h_axlims,'UserData');
   else
      origaxlims = axlims;
   end

   h_dlg = figure( ...
      'Visible','off', ...
      'Name','Axis Properties', ...
      'Units','pixels', ...
      'Position',[250 300 450 110+htval], ...
      'DefaultUiControlUnits','pixels', ...
      'MenuBar','none', ...
      'Resize','off', ...
      'NumberTitle','off', ...
      'Tag','newaxisdlg', ...
      'UserData',[{h},{plottype}]);

   colorspec = get(h_dlg,'Color');

   h_text = uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[150 90+htval 55 18], ...
      'String','Min', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[210 90+htval 55 18], ...
      'String','Max', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[270 90+htval 55 18], ...
      'String','Start', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[330 90+htval 55 18], ...
      'String','Interval', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[392 90+htval 50 18], ...
      'String','Reverse', ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[10 70+htval 140 18], ...
      'String',xlblstr, ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Position',[10 40+htval 140 18], ...
      'String',ylblstr, ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','text', ...
      'Visible',zvis, ...
      'Position',[10 10+htval 140 18], ...
      'String',zlblstr, ...
      'HorizontalAlignment','center', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec);

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[150 70+htval 55 20], ...
      'String',num2str(axlims(1)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','ex_min');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[210 70+htval 55 20], ...
      'String',num2str(axlims(2)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','ex_max');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[270 70+htval 55 20], ...
      'String',num2str(axlims(3)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','ex_start');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[330 70+htval 55 20], ...
      'String',num2str(axlims(4)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','ex_int');

   uicontrol(h_dlg, ...
      'Style','checkbox', ...
      'Enable',checkvis, ...
      'Position',[412 70+htval 10 20], ...
      'Value',xdir, ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec, ...
      'Tag','ex_dir');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[150 40+htval 55 20], ...
      'String',num2str(axlims(5)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','em_min');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[210 40+htval 55 20], ...
      'String',num2str(axlims(6)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','em_max');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[270 40+htval 55 20], ...
      'String',num2str(axlims(7)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','em_start');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Position',[330 40+htval 55 20], ...
      'String',num2str(axlims(8)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','em_int');

   uicontrol(h_dlg, ...
      'Style','checkbox', ...
      'Enable',checkvis, ...
      'Position',[412 40+htval 10 20], ...
      'Value',ydir, ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec, ...
      'Tag','em_dir');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Visible',zvis, ...
      'Position',[150 10+htval 55 20], ...
      'String',num2str(axlims(9)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','fl_min');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Visible',zvis, ...
      'Position',[210 10+htval 55 20], ...
      'String',num2str(axlims(10)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','fl_max');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Visible',zvis, ...
      'Position',[270 10+htval 55 20], ...
      'String',num2str(axlims(11)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','fl_start');

   uicontrol(h_dlg, ...
      'Style','edit', ...
      'Visible',zvis, ...
      'Position',[330 10+htval 55 20], ...
      'String',num2str(axlims(12)), ...
      'HorizontalAlignment','left', ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',[1 1 1], ...
      'Tag','fl_int');

   uicontrol(h_dlg, ...
      'Style','checkbox', ...
      'Visible',checkvis, ...
      'Position',[412 10+htval 10 20], ...
      'Value',zdir, ...
      'ForegroundColor',[0 0 0], ...
      'BackgroundColor',colorspec, ...
      'Tag','fl_dir');

   uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[10 5 60 25], ...
      'String','Cancel', ...
      'Tag','cmdCancel', ...
      'UserData',[xdir ydir zdir], ...
      'Callback','newaxisdlg(''cancel'')');

   uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[195 5 60 25], ...
      'String','Default', ...
      'Tag','cmdDefault', ...
      'UserData',origaxlims, ...
      'Callback','newaxisdlg(''default'')');

   uicontrol(h_dlg, ...
      'Style','pushbutton', ...
      'Position',[380 5 60 25], ...
      'String','Apply', ...
      'Tag','cmdApply', ...
      'UserData',axlims, ...
      'Callback','newaxisdlg(''eval'')');

   set(h_dlg,'Visible','on'); drawnow

else

   h_dlg = findobj('Tag','newaxisdlg');

   data = get(h_dlg,'UserData');
   h_fig = data{1};
   plottype = data{2};

   tags = [{'ex_min'} {'ex_max'} {'ex_start'} {'ex_int'} ...
         {'em_min'} {'em_max'} {'em_start'} {'em_int'} ...
         {'fl_min'} {'fl_max'} {'fl_start'} {'fl_int'}];

   boxes = [{'ex_dir'} {'em_dir'} {'fl_dir'}];

   if strcmp(op,'cancel')

      close(h_dlg)

      figure(h_fig)

   elseif strcmp(op,'default')

      h_default = findobj(h_dlg,'Tag','cmdDefault');
      h_cancel = findobj(h_dlg,'Tag','cmdCancel');

      axlims = get(h_default,'UserData');
      axisdir = get(h_cancel,'UserData');

      for n = 1:length(tags)
         h_edit = findobj(h_dlg,'Tag',char(tags{n}));
         set(h_edit,'String',num2str(axlims(n)))
      end

      for n = 1:length(boxes)
         h_box = findobj(h_dlg,'Tag',char(boxes{n}));
         set(h_box,'Value',axisdir(n))
      end

   elseif strcmp(op,'eval')

      h_apply = findobj(h_dlg,'Tag','cmdApply');
      h_cancel = findobj(h_dlg,'Tag','cmdCancel');

      initaxlims = get(h_apply,'UserData');
      axlims = initaxlims;

      initaxdir = get(h_cancel,'UserData');
      axdir = initaxdir;

      for n = 1:length(tags)
         h_edit = findobj(h_dlg,'Tag',char(tags{n}));
         val = str2num(deblank(get(h_edit,'String')));
         if ~isempty(val)
            axlims(n) = val;
         end
      end

      for n = 1:length(boxes)
         h_box = findobj(h_dlg,'Tag',char(boxes{n}));
         axdir(n) = get(h_box,'Value');
      end

      close(h_dlg)

      figure(h_fig)

      drawnow

      %update plot if values changed

      if strcmp(plottype,'3d')  %3d EEM plot

         if sum(axdir ~= initaxdir) > 0

            axdirstr = [{'normal'} {'reverse'}];

            set(gca, ...
               'XDir',char(axdirstr{axdir(1)+1}), ...
               'YDir',char(axdirstr{axdir(2)+1}), ...
               'ZDir',char(axdirstr{axdir(3)+1}))

         end

         if sum(axlims ~= initaxlims) > 0

            %update axis and color bar
            newaxis([axlims(1:2) axlims(5:6) axlims(9:10)])

            %apply custom ticks
            set(gca, ...
               'XTick',[axlims(3):axlims(4):axlims(2)], ...
               'YTick',[axlims(7):axlims(8):axlims(6)], ...
               'ZTick',[axlims(11):axlims(12):axlims(10)])

            %update Z position of displayed polygons
            h_polys = findobj(gcf,'Tag','polyline');
            if ~isempty(h_polys)
               for n = 1:size(h_polys)
                  zdata = get(h_polys(n),'ZData');
                  set(h_polys(n),'ZData',ones(size(zdata)).*(axlims(10)+eps))
               end
            end

            %update contourline Z positions
            contourlines('update');

            %update peaklabel Z positions
            editpeaks('update');

         end

      else  %2d Ex/Em plot

         axis([axlims(1:2) axlims(5:6)])

         set(gca, ...
            'XTick',[axlims(3):axlims(4):axlims(2)], ...
            'YTick',[axlims(7):axlims(8):axlims(6)])

      end

   end

end