function scatterdlg(op,inittol)
%Scatter correction tolerance dialog function
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 10/5/2001

if nargin == 0
   op = 'init';
end

if strcmp(op,'init')

   h_fig = gcf;

   h_dlg = findobj('Tag','dlgScatter');

   if ~isempty(h_dlg)
      close(h_dlg)
   end

   if ~exist('inittol')
      inittol = [1000 12;16 16;18 18;18 18];
   end

   tol = inittol;  %set default scatter tolerances

   h_correct = findobj(h_fig,'Tag','editScatter');
   if ~isempty(h_correct)
      correctstr = get(h_correct,'String');
      scattertol = str2num(correctstr);
      if ~isempty(scattertol)
         if size(scattertol,1) == 4 & size(scattertol,2) == 2
            tol = scattertol;  %use dialog values instead of defaults
         end
      end
   end

   screen = get(0,'screensize');

   bgcolor = [0.9 0.9 0.9];

   h_dlg = figure('Visible','off', ...
      'Color',bgcolor, ...
      'KeyPressFcn','figure(gcf)', ...
      'MenuBar','none', ...
      'Name','Scatter Tolerances', ...
      'NumberTitle','off', ...
      'Position',[screen(3)-325 max(screen(4)-400,60) 320 210], ...
      'Tag','dlgScatter', ...
      'ToolBar','none', ...
      'Resize','off', ...
      'UserData',h_fig);

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','center', ...
      'Position',[2 180 316 20], ...
      'String','Scatter Peak Boundaries Relative to Peak Emission', ...
      'FontWeight','bold', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','left', ...
      'Position',[25 135 125 20], ...
      'String','Rayleigh (1st order)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','left', ...
      'Position',[25 105 125 20], ...
      'String','Raman (1st order)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','left', ...
      'Position',[25 75 125 20], ...
      'String','Rayleigh (2nd order)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','left', ...
      'Position',[25 45 125 20], ...
      'String','Raman (2nd order)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','center', ...
      'Position',[150 155 60 20], ...
      'String','Below (nm)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',bgcolor, ...
      'ForegroundColor',[0 0 0], ...
      'HorizontalAlignment','center', ...
      'Position',[230 155 60 20], ...
      'String','Above (nm)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[150 135 60 20], ...
      'String',num2str(tol(1,1)), ...
      'Style','edit', ...
      'Tag','editR1C1');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[230 135 60 20], ...
      'String',num2str(tol(1,2)), ...
      'Style','edit', ...
      'Tag','editR1C2');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[150 105 60 20], ...
      'String',num2str(tol(2,1)), ...
      'Style','edit', ...
      'Tag','editR2C1');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[230 105 60 20], ...
      'String',num2str(tol(2,2)), ...
      'Style','edit', ...
      'Tag','editR2C2');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[150 75 60 20], ...
      'String',num2str(tol(3,1)), ...
      'Style','edit', ...
      'Tag','editR3C1');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[230 75 60 20], ...
      'String',num2str(tol(3,2)), ...
      'Style','edit', ...
      'Tag','editR3C2');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[150 45 60 20], ...
      'String',num2str(tol(4,1)), ...
      'Style','edit', ...
      'Tag','editR4C1');

   h1 = uicontrol('Parent',h_dlg, ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[0 0 0], ...
      'Position',[230 45 60 20], ...
      'String',num2str(tol(4,2)), ...
      'Style','edit', ...
      'Tag','editR4C2');

   h1 = uicontrol('Parent',h_dlg, ...
      'FontWeight','bold', ...
      'ForegroundColor',[0 0 0], ...
      'Position',[240 4 75 25], ...
      'String','Accept', ...
      'Tag','cmdAccept', ...
      'Callback','scatterdlg(''eval'')');

   h1 = uicontrol('Parent',h_dlg, ...
      'FontWeight','bold', ...
      'ForegroundColor',[0 0 0], ...
      'Position',[5 4 75 25], ...
      'String','Cancel', ...
      'Tag','cmdCancel', ...
      'Callback','scatterdlg(''cancel'')');

   h1 = uicontrol('Parent',h_dlg, ...
      'FontWeight','bold', ...
      'ForegroundColor',[0 0 0], ...
      'Position',[122.5 4 75 25], ...
      'String','Default', ...
      'Tag','cmdDefault', ...
      'UserData',inittol, ...
      'Callback','scatterdlg(''default'')');

   set(h_dlg,'Visible','on')

else

   h_dlg = findobj('Tag','dlgScatter');
   h_fig = get(h_dlg,'UserData');

   if strcmp(op,'cancel')

      close(h_dlg)
      figure(h_fig)

   elseif strcmp(op,'default')

      h_default = findobj(h_dlg,'Tag','cmdDefault');
      inittol = get(h_default,'UserData');
      inittol = inittol(:);

      handles = ['editR1C1';'editR2C1';'editR3C1';'editR4C1'; ...
            'editR1C2';'editR2C2';'editR3C2';'editR4C2'];

      for n = 1:size(handles,1)
         h = findobj(h_dlg,'Tag',handles(n,:));
         set(h,'String',num2str(inittol(n)))
      end

      drawnow

   elseif strcmp(op,'eval')

      h_accept = findobj(h_dlg,'Tag','cmdAccept');

      handles = ['editR1C1';'editR2C1';'editR3C1';'editR4C1'; ...
            'editR1C2';'editR2C2';'editR3C2';'editR4C2'];

      scattertol = ones(8,1) .* NaN;

      for n = 1:size(handles,1)
         h = findobj(h_dlg,'Tag',handles(n,:));
         val = str2num(get(h,'String'));
         if ~isempty(val)
            scattertol(n) = val;
         end
      end

      if length(find(isnan(scattertol))) == 0  %valid data

         close(h_dlg)
         figure(h_fig)

         correctstr = ['[' num2str(scattertol(1)) ' ' num2str(scattertol(5)) ';' ...
               num2str(scattertol(2)) ' ' num2str(scattertol(6)) ';' ...
               num2str(scattertol(3)) ' ' num2str(scattertol(7)) ';' ...
               num2str(scattertol(4)) ' ' num2str(scattertol(8)) ']'];

         h_scatterval = findobj(h_fig,'Tag','editScatter');

         if ~isempty(h_scatterval)
            set(h_scatterval,'String',correctstr)
         end

         drawnow

      else

         errorbox('init','One or more entries are invalid')

      end

   end

end


