function surfoptdlg(op)
%Surface object dialog box called by 'eemplot'
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 10/5/2001

if nargin == 0

   %clear prior instances of dialog
   h_dlg = findobj('Tag','surfoptdlg');
   if ~isempty(h_dlg)
      close(h_dlg)
   end

   h = gcf;

   h_s = findobj(gca,'Type','surface');

   if ~isempty(h_s)

      edgecolor = get(h_s,'EdgeColor');
      facecolor = get(h_s,'FaceColor');
      meshstyle = get(h_s,'MeshStyle');
      edgelight = get(h_s,'EdgeLighting');
      facelight = get(h_s,'FaceLighting');
      backfacelight = get(h_s,'BackFaceLighting');

      h_l = findobj(gca,'type','light');
      if ~isempty(h_l)
         lightval = 1;
         lightopt = 'on';
         [lightaz,lightel] = lightangle(h_l(1));
      else
         lightval = 0;
         lightopt = 'off';
         lightaz = 90;
         lightel = 65;
      end

      vals = ones(1,6);
      edgebutton = 'off';
      edgebuttonclr = [0 0 0];
      facebutton = 'off';
      facebuttonclr = [1 1 1];

      if ~isstr(edgecolor)
         vals(1) = 4;
         edgebutton = 'on';
         edgebuttonclr = edgecolor;
      else
         switch edgecolor
         case 'none',
            vals(1) = 1;
         case 'flat',
            vals(1) = 2;
         otherwise,
            vals(1) = 3;
         end
      end

      if ~isstr(facecolor)
         vals(2) = 4;
         facebutton = 'on';
         facebuttonclr = facecolor;
      else
         switch facecolor
         case 'none',
            vals(2) = 1;
         case 'flat',
            vals(2) = 2;
         otherwise,
            vals(2) = 3;
         end
      end

      switch meshstyle
      case 'both'
         vals(3) = 1;
      case 'row'
         vals(3) = 2;
      otherwise
         vals(3) = 3;
      end

      switch edgelight
      case 'none',
         vals(4) = 1;
      case 'flat',
         vals(4) = 2;
      case 'gouraud',
         vals(4) = 3;
      otherwise,
         vals(4) = 4;
      end

      switch facelight
      case 'none',
         vals(5) = 1;
      case 'flat',
         vals(5) = 2;
      case 'gouraud',
         vals(5) = 3;
      otherwise,
         vals(5) = 4;
      end

      switch backfacelight
      case 'unlit',
         vals(6) = 1;
      case 'lit',
         vals(6) = 2;
      otherwise,
         vals(6) = 3;
      end

      h_dlg = figure( ...
         'Visible','off', ...
         'Name','Surface Options', ...
         'Menubar','none', ...
         'NumberTitle','off', ...
         'Resize','off', ...
         'Units','pixels', ...
         'Position',[200 300 320 300], ...
         'DefaultUiControlUnits','normal', ...
         'Tag','surfoptdlg', ...
         'UserData',[{h} {h_s} {vals} {edgebuttonclr} {facebuttonclr}]);

      colorspec = get(h_dlg,'Color');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .9 .35 .06], ...
         'String','Facet Edge Color', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','popup', ...
         'Position',[.37 .9 .33 .07], ...
         'String','None|Flat|Interpolated|Uniform Color', ...
         'Value',vals(1), ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[1 1 1], ...
         'Tag','edge_pop', ...
         'Callback','surfoptdlg(''buttonvis'')');

      uicontrol(h_dlg, ...
         'Visible',edgebutton, ...
         'Style','pushbutton', ...
         'Position',[.72 .9 .18 .07], ...
         'String','Pick Color', ...
         'ForegroundColor',[0 0 0], ...
         'Tag','edge_btn', ...
         'Callback','surfoptdlg(''edge_clr'')');

      uicontrol(h_dlg, ...
         'Visible',edgebutton, ...
         'Style','text', ...
         'Position',[.92 .9 .07 .07], ...
         'String','', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',edgebuttonclr, ...
         'Tag','edge_clr');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .8 .35 .06], ...
         'String','Facet Face Color', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','popup', ...
         'Position',[.37 .8 .33 .07], ...
         'String','None|Flat|Interpolated|Uniform Color', ...
         'Value',vals(2), ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[1 1 1], ...
         'Tag','face_pop', ...
         'Callback','surfoptdlg(''buttonvis'')');

      uicontrol(h_dlg, ...
         'Visible',facebutton, ...
         'Style','pushbutton', ...
         'Position',[.72 .8 .18 .07], ...
         'String','Pick Color', ...
         'ForegroundColor',[0 0 0], ...
         'Tag','face_btn', ...
         'Callback','surfoptdlg(''face_clr'')');

      uicontrol(h_dlg, ...
         'Visible',facebutton, ...
         'Style','text', ...
         'Position',[.92 .8 .07 .07], ...
         'String','', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',facebuttonclr, ...
         'Tag','face_clr');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .7 .35 .06], ...
         'String','Mesh Style', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','popup', ...
         'Position',[.37 .7 .4 .07], ...
         'String','Both Directions|Emission Only|Excitation Only', ...
         'Value',vals(3), ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[1 1 1], ...
         'Tag','mesh');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .55 .35 .06], ...
         'String','Surface Lighting', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','checkbox', ...
         'Position',[.35 .55 .3 .06], ...
         'String','Enable Lighting', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec, ...
         'Value',lightval, ...
         'Tag','chklighting', ...
         'UserData',[lightval,lightaz,lightel], ...
         'Callback','surfoptdlg(''buttonvis'')');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .45 .28 .06], ...
         'String','Light Azimuth', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[.48 .45 .25 .06], ...
         'String','Light Elevation', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','edit', ...
         'Position',[.28 .45 .2 .07], ...
         'String',num2str(lightaz), ...
         'BackgroundColor',[1 1 1], ...
         'Enable',lightopt, ...
         'Tag','lightaz');

      uicontrol(h_dlg, ...
         'Style','edit', ...
         'BackgroundColor',[1 1 1], ...
         'Position',[.73 .45 .2 .07], ...
         'String',num2str(lightel), ...
         'Enable',lightopt, ...
         'Tag','lightel');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .35 .35 .06], ...
         'String','Edge Lighting', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','popup', ...
         'Position',[.37 .35 .4 .07], ...
         'String','None|Flat|Gouraud Model|Phong Model', ...
         'Value',vals(4), ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[1 1 1], ...
         'Enable',lightopt, ...
         'Tag','edgelight');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .25 .35 .06], ...
         'String','Face Lighting', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','popup', ...
         'Position',[.37 .25 .4 .07], ...
         'String','None|Flat|Gouraud Model|Phong Model', ...
         'Value',vals(5), ...
         'Enable',lightopt, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[1 1 1], ...
         'Tag','facelight');

      uicontrol(h_dlg, ...
         'Style','text', ...
         'Position',[0 .15 .35 .06], ...
         'String','Back Face Lighting', ...
         'HorizontalAlignment','center', ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',colorspec);

      uicontrol(h_dlg, ...
         'Style','popup', ...
         'Position',[.37 .15 .4 .07], ...
         'String','Unlit|Lit|Reverse Lit', ...
         'Value',vals(6), ...
         'Enable',lightopt, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[1 1 1], ...
         'Tag','backface');

      uicontrol(h_dlg, ...
         'Style','pushbutton', ...
         'Position',[0 0 .25 .08], ...
         'String','Cancel', ...
         'Callback','surfoptdlg(''cancel'')');

      uicontrol(h_dlg, ...
         'Style','pushbutton', ...
         'Position',[.375 0 .25 .08], ...
         'String','Default', ...
         'Callback','surfoptdlg(''default'')');

      uicontrol(h_dlg, ...
         'Style','pushbutton', ...
         'Position',[.75 0 .25 .08], ...
         'String','Apply', ...
         'Callback','surfoptdlg(''eval'')');

      set(h_dlg,'Visible','on'); drawnow

   end

else

   h_dlg = findobj('Tag','surfoptdlg');
   data = get(h_dlg,'UserData');

   tags = [{'edge_pop'} {'face_pop'} {'mesh'} ...
         {'edgelight'} {'facelight'} {'backface'}];

   if strcmp(op,'cancel')

      close(h_dlg)

      figure(data{1})

   elseif strcmp(op,'default')

      vals = [1 3 1 1 2 3];

      for n = 1:length(tags)
         h_popup = findobj(h_dlg,'Tag',char(tags{n}));
         set(h_popup,'Value',vals(n))
      end

      h_lighting = findobj(h_dlg,'Tag','chklighting');
      lightdata = get(h_lighting,'UserData');
      set(h_lighting,'Value',lightdata(1))

      h_lightaz = findobj(h_dlg,'Tag','lightaz');
      set(h_lightaz,'String',num2str(lightdata(2)))

      h_lightel = findobj(h_dlg,'Tag','lightel');
      set(h_lightel,'String',num2str(lightdata(3)))

      h_edgeclr = findobj(h_dlg,'Tag','edge_clr');
      set(h_edgeclr,'BackgroundColor',[0 0 0])

      h_faceclr = findobj(h_dlg,'Tag','face_clr');
      set(h_faceclr,'BackgroundColor',[0 0 .8])

      surfoptdlg('buttonvis')

   elseif strcmp(op,'eval')

      vals = data{3};

      newvals = vals;

      for n = 1:length(tags)
         h_popup = findobj(h_dlg,'Tag',char(tags{n}));
         newvals(n) = get(h_popup,'Value');
      end

      h_lightval = findobj(h_dlg,'Tag','chklighting');
      lightval = get(h_lightval,'Value');
      if lightval == 1
         h_lightaz = findobj(h_dlg,'Tag','lightaz');
         lightaz = str2num(get(h_lightaz,'String'));
         h_lightel = findobj(h_dlg,'Tag','lightel');
         lightel = str2num(get(h_lightel,'String'));
      end

      h_edgeclr = findobj(h_dlg,'Tag','edge_clr');
      edgeclr = get(h_edgeclr,'BackgroundColor');

      h_faceclr = findobj(h_dlg,'Tag','face_clr');
      faceclr = get(h_faceclr,'BackgroundColor');

      close(h_dlg)

      figure(data{1})
      drawnow

      switch newvals(1)
      case 1,
         edgecolor = 'none';
      case 2,
         edgecolor = 'flat';
      case 3,
         edgecolor = 'interp';
      otherwise,
         edgecolor = edgeclr;
      end

      switch newvals(2)
      case 1,
         facecolor = 'none';
      case 2,
         facecolor = 'flat';
      case 3,
         facecolor = 'interp';
      otherwise,
         facecolor = faceclr;
      end

      switch newvals(3)
      case 1,
         meshstyle = 'both';
      case 2,
         meshstyle = 'row';
      otherwise,
         meshstyle = 'col';
      end

      switch newvals(4)
      case 1,
         edgelight = 'none';
      case 2,
         edgelight = 'flat';
      case 3,
         edgelight = 'gouraud';
      otherwise,
         edgelight = 'phong';
      end

      switch newvals(5)
      case 1,
         facelight = 'none';
      case 2,
         facelight = 'flat';
      case 3,
         facelight = 'gouraud';
      otherwise,
         facelight = 'phong';
      end

      switch newvals(6)
      case 1,
         backfacelight = 'unlit';
      case 2,
         backfacelight = 'lit';
      otherwise,
         backfacelight = 'reverselit';
      end

      set(data{2}, ...
         'EdgeColor',edgecolor, ...
         'FaceColor',facecolor, ...
         'MeshStyle',meshstyle, ...
         'EdgeLighting',edgelight, ...
         'FaceLighting',facelight, ...
         'BackFaceLighting',backfacelight);

      h_l = findobj(gca,'type','light');

      if lightval == 1
         if isempty(h_l)
            h_l = light;
         else
            h_l = h_l(1);
         end
         lightangle(h_l,lightaz,lightel)
      else  %delete any lights
         if ~isempty(h_l)
            delete(h_l)
         end
      end

      drawnow

   elseif strcmp(op,'buttonvis')

      h_lightval = findobj(h_dlg,'Tag','chklighting');

      h_lightctrls = [findobj(h_dlg,'Tag','lightaz'); ...
         findobj(h_dlg,'Tag','lightel'); ...
         findobj(h_dlg,'Tag','edgelight'); ...
         findobj(h_dlg,'Tag','facelight'); ...
         findobj(h_dlg,'Tag','backface')];

      h_edgepop = findobj(h_dlg,'Tag','edge_pop');
      h_edgebtn = findobj(h_dlg,'Tag','edge_btn');
      h_edgeclr = findobj(h_dlg,'Tag','edge_clr');

      h_facepop = findobj(h_dlg,'Tag','face_pop');
      h_facebtn = findobj(h_dlg,'Tag','face_btn');
      h_faceclr = findobj(h_dlg,'Tag','face_clr');

      edgeval = get(h_edgepop,'Value');
      if edgeval < 4
         set(h_edgebtn,'Visible','off')
         set(h_edgeclr,'Visible','off')
      else
         set(h_edgebtn,'Visible','on')
         set(h_edgeclr,'Visible','on')
      end

      faceval = get(h_facepop,'Value');
      if faceval < 4
         set(h_facebtn,'Visible','off')
         set(h_faceclr,'Visible','off')
      else
         set(h_facebtn,'Visible','on')
         set(h_faceclr,'Visible','on')
      end

      lightval = get(h_lightval,'Value');
      if lightval == 1
         set(h_lightctrls,'Enable','on')
      else
         set(h_lightctrls,'Enable','off')
      end

      drawnow

   elseif strcmp(op,'edge_clr') | strcmp(op,'face_clr')

      if strcmp(op,'edge_clr')
         h_clr = findobj(h_dlg,'Tag','edge_clr');
         str = 'facet edge';
      else
         h_clr = findobj(h_dlg,'Tag','face_clr');
         str = 'facet face';
      end

      c = get(h_clr,'BackgroundColor');

      c_new = uisetcolor(c,['Select ' str ' color']);

      if ~isempty(c_new)
         set(h_clr,'BackgroundColor',c_new);
      end

   end

end