function textedit(op)
%syntax:  textedit(op)
%
%Text editing dialog box, to be used as a callback function associated
%with text objects.
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 11-14-99

if nargin == 0

   h_dlg = findobj('Tag','dlgTextEdit');
   if ~isempty(h_dlg)
      close(h_dlg)
   end

   h_cbo = gcbo;

   objtype = get(h_cbo,'Type');

   if strcmp(lower(objtype),'text')
      str = get(h_cbo,'String');
      fontname = get(h_cbo,'FontName');
      fontunits = get(h_cbo,'FontUnits');
      fontsize = get(h_cbo,'FontSize');
      fontweight = get(h_cbo,'FontWeight');
      fontangle = get(h_cbo,'FontAngle');
      fontcolor = get(h_cbo,'Color');
      fontrotate = get(h_cbo,'Rotation');
      interpreter = get(h_cbo,'Interpreter');
   else
      str = '';
      fontname = 'Helvetica';
      fontunits = 'points';
      fontsize = 10;
      fontweight = 'normal';
      fontangle = 'normal';
      fontcolor = [0 0 0];
      fontrotate = 0;
      interpreter = 'none';
   end

   if fontcolor ~= [1 1 1]
      backcolor = [1 1 1];
   else
      backcolor = [.6 .6 .6];
   end

   if strcmp(interpreter,'tex')
      texval = 1;
   else
      texval = 0;
   end

   h_dlg = figure('Units','points', ...
      'Visible','off', ...
      'Color',[0.8 0.8 0.8], ...
      'KeyPressFcn','figure(gcf)', ...
      'MenuBar','none', ...
      'Name','Edit Text', ...
      'NumberTitle','off', ...
      'Position',[142.5 70.5 411 103.5], ...
      'Tag','dlgTextEdit', ...
      'UserData',gcf);

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'BackgroundColor',backcolor, ...
      'ForegroundColor',fontcolor, ...
      'FontName',fontname, ...
      'FontUnits',fontunits, ...
      'FontSize',fontsize, ...
      'FontWeight',fontweight, ...
      'FontAngle',fontangle, ...
      'ListboxTop',0, ...
      'Max',5, ...
      'Min',1, ...
      'Position',[3.75 29.25 401.25 45.75], ...
      'String',str, ...
      'Style','edit', ...
      'Tag','EditBox', ...
      'UserData',h_cbo);

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'Callback','textedit(''font'')', ...
      'ListboxTop',0, ...
      'Position',[15 79.5 60 18.75], ...
      'String','Font Attributes', ...
      'Tag','font');

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'Callback','textedit(''color'')', ...
      'ListboxTop',0, ...
      'Position',[83.25 79.5 49.5 18.75], ...
      'String','Text Color', ...
      'Tag','color');

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'Callback','textedit(''eval'')', ...
      'ListboxTop',0, ...
      'Position',[360 5 45 18], ...
      'String','Accept', ...
      'Tag','accept');

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'Callback','textedit(''cancel'')', ...
      'ListboxTop',0, ...
      'Position',[5 5 45 18], ...
      'String','Cancel', ...
      'Tag','cancel');

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'BackgroundColor',[0.8 0.8 0.8], ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[150 80 50 14], ...
      'String',' Rotation (°)', ...
      'Style','text');

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ListboxTop',0, ...
      'Position',[200 81 38 15], ...
      'Style','edit', ...
      'String',num2str(fontrotate), ...
      'Tag','Rotate');

   h1 = uicontrol('Parent',h_dlg, ...
      'Units','points', ...
      'BackgroundColor',[0.8 0.8 0.8], ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[260 81 100 14], ...
      'String','TeX Interpreter', ...
      'Style','checkbox', ...
      'Value',texval, ...
      'Tag','texval');

   set(h_dlg,'Visible','on')

else

   h_dialog = findobj('Tag','dlgTextEdit');
   h_fig = get(h_dialog,'UserData');
   h_edit = findobj(h_dialog,'Tag','EditBox');

   if strcmp(op,'cancel')

      close(h_dialog)
      figure(h_fig)

   elseif strcmp(op,'font')

      uisetfont(h_edit,'Font Attributes');

   elseif strcmp(op,'color')

      uisetcolor(h_edit,'Font Color');

   elseif strcmp(op,'eval')

      str = get(h_edit,'String');
      fontname = get(h_edit,'FontName');
      fontunits = get(h_edit,'FontUnits');
      fontsize = get(h_edit,'FontSize');
      fontweight = get(h_edit,'FontWeight');
      fontangle = get(h_edit,'FontAngle');
      fontcolor = get(h_edit,'ForegroundColor');

      h_rotate = findobj(h_dialog,'Tag','Rotate');
      rotatestr = get(h_rotate,'String');
      fontrotate = 0;
      if ~isempty(rotatestr)
         fontrotate = str2num(rotatestr);
      end

      h_interp = findobj(h_dialog,'Tag','texval');
      texval = get(h_interp,'Value');
      if texval == 1
         interpreter = 'tex';
      else
         interpreter = 'none';
      end

      h_cbo = get(h_edit,'UserData');

      set(h_cbo, ...
         'String',str, ...
         'FontName',fontname, ...
         'FontUnits',fontunits, ...
         'FontSize',fontsize, ...
         'FontWeight',fontweight, ...
         'FontAngle',fontangle, ...
         'Color',fontcolor, ...
         'Rotation',fontrotate, ...
         'Interpreter',interpreter);

      close(h_dialog)
      figure(h_fig)
      drawnow

   end

end
