function viewcontrols(op)
%Adds uicontrols to a 3D plot figure for adjusting the azimuth and elevation
%
%Notes:  1) function file must be in Matlab search path
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last revised 6/25/2000

if nargin == 0

   %shift plot axis to accomodate buttons, fields
   axpos = get(gca,'Position');
   set(gca, ...
      'Position',[axpos(1)+0.07 axpos(2)+.07 axpos(3) axpos(4)-.07])

   %shift colorbar to match new axis position
   h_bar = findobj(gcf,'Tag','Colorbar');
   if ~isempty(h_bar)
      barpos = get(h_bar(1),'Position');
      set(h_bar,'Position',[axpos(1)+axpos(3)+0.05 axpos(2)+.07 barpos(3) axpos(4)-.07])
   end

   %create controls
   uicontrol('Style','frame', ...
      'Units','normal', ...
      'Position',[0 0 .195 .05], ...
      'BackgroundColor','w', ...
      'ForegroundColor','k');

   uicontrol('Style','text', ...
      'Units','normal', ...
      'Position',[.01 .005 .1 .035], ...
      'String','Azimuth', ...
      'BackgroundColor','w', ...
      'ForegroundColor','k', ...
      'HorizontalAlignment','center');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.11 .005 .035 .04], ...
      'String','-', ...
      'TooltipString','Shift azimuth counter-clockwise by selected percentage', ...
      'Callback','viewcontrols az-');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.15 .005 .035 .04], ...
      'String','+', ...
      'TooltipString','Shift azimuth clockwise by selected percentage', ...
      'Callback','viewcontrols az+');

   uicontrol('Style','frame', ...
      'Units','normal', ...
      'Position',[.2 0 .205 .05], ...
      'BackgroundColor','w', ...
      'ForegroundColor','k');

   uicontrol('Style','text', ...
      'Units','normal', ...
      'Position',[.21 .005 .1 .035], ...
      'String','Elevation', ...
      'BackgroundColor','w', ...
      'ForegroundColor','k', ...
      'HorizontalAlignment','center');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.32 .005 .035 .04], ...
      'String','-', ...
      'TooltipString','Lower elevation by selected percentage', ...
      'Callback','viewcontrols el-');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.36 .005 .035 .04], ...
      'String','+', ...
      'TooltipString','Raise elevation by selected percentage', ...
      'Callback','viewcontrols el+');

   uicontrol('Style','slider', ...
      'Units','normal', ...
      'Position',[.42 0 .24 .035], ...
      'Min',0, ...
      'Max',30, ...
      'Value',10, ...
      'Tag','factor', ...
      'UserData',10, ...
      'TooltipString','Adjust percentage for azimuth/elevation changes', ...
      'Callback','viewcontrols slider');

   uicontrol('Style','text', ...
      'Units','normal', ...
      'Position',[.445 .035 .032 .03], ...
      'String','0°', ...
      'HorizontalAlignment','left', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol('Style','text', ...
      'Units','normal', ...
      'Position',[.5 .035 .032 .03], ...
      'String','10°', ...
      'HorizontalAlignment','left', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol('Style','text', ...
      'Units','normal', ...
      'Position',[.555 .035 .032 .03], ...
      'String','20°', ...
      'HorizontalAlignment','left', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol('Style','text', ...
      'Units','normal', ...
      'Position',[.61 .035 .032 .03], ...
      'String','30°', ...
      'HorizontalAlignment','left', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.68 0 .06 .045], ...
      'String','Em/Ex', ...
      'TooltipString','Change to Emission vs Excitation plot (top view)', ...
      'Callback','viewcontrols top');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.75 0 .06 .045], ...
      'String','Fl/Ex', ...
      'TooltipString','Change to Fluorescence vs Excitation plot format (side view)', ...
      'Callback','viewcontrols xview');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.82 0 .06 .045], ...
      'String','Fl/Em', ...
      'TooltipString','Change to Fluorescence vs Emission plot format (side view)', ...
      'Callback','viewcontrols yview');

   uicontrol('Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.91 0 .09 .045], ...
      'String','3D View', ...
      'TooltipString','Reset to default 3D viewpoint', ...
      'Callback','viewcontrols rst');

   set(gcf, ...
      'WindowButtonDownFcn','clickpos;', ...
      'WindowButtonUpFcn','', ...
      'Pointer','crosshair')

   uicontrol(gcf, ...
      'Style','frame', ...
      'Units','normal', ...
      'Position',[.001 .7 .115 .10], ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol(gcf, ...
      'Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.006 .75 .105 .045], ...
      'String','Lambda-Ex', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w', ...
      'Callback','sliceplot(''emplot'',''linear'')', ...
      'TooltipString','Plot emission at last excitation value (EEM slice)');

   uicontrol(gcf, ...
      'Style','text', ...
      'Units','normal', ...
      'Position',[.005 .705 .105 .045], ...
      'String','', ...
      'ForegroundColor',[0 0 .8], ...
      'BackgroundColor','w', ...
      'Tag','lambda-ex');

   uicontrol(gcf, ...
      'Style','frame', ...
      'Units','normal', ...
      'Position',[.001 .55 .115 .10], ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol(gcf, ...
      'Style','pushbutton', ...
      'Units','normal', ...
      'Position',[.006 .6 .105 .045], ...
      'String','Lambda-Em', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w', ...
      'Callback','sliceplot(''explot'',''linear'')', ...
      'TooltipString','Plot excitation at last emission value (EEM slice)');

   uicontrol(gcf, ...
      'Style','text', ...
      'Units','normal', ...
      'Position',[.005 .555 .105 .045], ...
      'String','', ...
      'ForegroundColor',[0 0 .8], ...
      'BackgroundColor','w', ...
      'Tag','lambda-em');

   uicontrol(gcf, ...
      'Style','frame', ...
      'Units','normal', ...
      'Position',[.001 .4 .115 .10], ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol(gcf, ...
      'Style','text', ...
      'Units','normal', ...
      'Position',[.005 .45 .105 .045], ...
      'String','Fluorescence', ...
      'ForegroundColor','k', ...
      'BackgroundColor','w');

   uicontrol(gcf, ...
      'Style','text', ...
      'Units','normal', ...
      'Position',[.005 .405 .105 .045], ...
      'String','', ...
      'ForegroundColor',[0 0 .8], ...
      'BackgroundColor','w', ...
      'Tag','fluor');

   viewcontrols rst

elseif strcmp(op,'hide')

   h_uihide = findobj(gcf,'Tag','uihide');

   if ~isempty(h_uihide)
      h_ctrls = findobj(gcf,'Type','uicontrol');
      if strcmp(get(h_uihide,'Label'),'Hide Plot Controls')
         set(h_uihide,'Label','Show Plot Controls')
         set(h_ctrls,'Visible','off')
      else
         set(h_uihide,'Label','Hide Plot Controls')
         set(h_ctrls,'Visible','on')
      end
   end

else

   h = findobj(gcf,'Tag','factor');
   val = get(h,'Value');

   if strcmp(op,'slider')

      lastval = get(h,'UserData');

      %round setting to nearest 1 degree after testing for terminal values
      if lastval > 0 & lastval < 30
         if val < lastval
            val = floor(val);
         else
            val = ceil(val);
         end
      elseif lastval == 0
         if val > 0
            val = 1;
         else
            val = 0;
         end
      else
         if val < 30
            val = floor(val);
         else
            val = 30;
         end
      end

      set(h,'Value',val,'UserData',val)   %set slider to reflect rounded value

   else

      %shift focus back to main axis if colorbar is current axis
      h_ax = findobj(gcf,'Type','axes');
      h_bar = findobj(gcf,'Tag','Colorbar');
      if length(h_bar) > 1
         h_bar = h_bar(end);
      end

      if ~isempty(h_bar)
         if h_bar == gca
            if h_bar == h_ax(1)
               axes(h_ax(2))
            else
               axes(h_ax(1))
            end
         end
      end

      [az,el] = view;

      if strcmp(get(gca,'XDir'),'normal')
         xdir = 0;
      else
         xdir = 1;
      end

      if strcmp(get(gca,'YDir'),'normal')
         ydir = 0;
      else
         ydir = 1;
      end

      if strcmp(get(gca,'ZDir'),'normal')
         zdir = 0;
      else
         zdir = 1;
      end

      %clear calculated fields
      h_field = findobj(gcf,'Tag','lambda-ex'); set(h_field,'String','')
      h_field = findobj(gcf,'Tag','lambda-em'); set(h_field,'String','')
      h_field = findobj(gcf,'Tag','fluor'); set(h_field,'String','')

      h_bar = findobj(gcf,'Tag','Colorbar');
      if length(h_bar) > 1
         h_bar = h_bar(end);
      end
      axpos = get(gca,'Position');
      barpos = get(h_bar,'Position');

      if ~isempty(h_bar)
         h_ylabel = get(h_bar,'YLabel');
         lblstr = get(h_ylabel,'String');
         h_zlabel = get(gca,'ZLabel');
         if el == 90
            if mlversion < 7
               set(h_bar,'Position',[axpos(1)+axpos(3)+.01 barpos(2:4)])
            end
            if isempty(lblstr)  %copy zlabel to colorbar ylabel if necessary
               set(h_ylabel, ...
                  'String',get(h_zlabel,'String'), ...
                  'Color',get(h_bar,'XColor'), ...
                  'FontSize',get(h_zlabel,'FontSize'), ...
                  'FontWeight',get(h_zlabel,'FontWeight'), ...
                  'ButtonDownFcn','textedit')
            end
         else
            if mlversion < 7
               set(h_bar,'Position',[axpos(1)+axpos(3)+.05 barpos(2:4)])
            end
            if ~isempty(lblstr)  %copy ylabel from colorbar to zlabel
               set(h_zlabel,'String',lblstr)
               set(h_ylabel,'String','')
            end
         end

      end

      if strcmp(op,'axislabels')

         h_x = get(gca,'XLabel');
         h_y = get(gca,'YLabel');
         h_z = get(gca,'ZLabel');

         if el == 90 | el == 270  %top/bottom view
            set(gca,'Box','on')
            set(h_x,'Visible','on')
            set(h_y,'Visible','on')
            set(h_z,'Visible','off')
         else
            set(h_z,'Visible','on')
            if az == 0 | az == 180
               set(gca,'Box','on')
               set(h_x,'Visible','on')
               set(h_y,'Visible','off')
            elseif az == 90 | az == 270
               set(gca,'Box','on')
               set(h_x,'Visible','off')
               set(h_y,'Visible','on')
            else
               set(gca,'Box','off')
               set(h_x,'Visible','on')
               set(h_y,'Visible','on')
            end
         end

      elseif strcmp(op,'clearfields')

         %do nothing - just process through initial operations

      else  %process viewpoint button clicks

         if strcmp(op,'top')

            el = 90;
            if [xdir ydir] == [1 1]
               az = 180;
            else
               az = 0;
            end

         elseif strcmp(op,'xview')

            el = 0;
            if xdir == 1
               az = 180;
            else
               az = 0;
            end

         elseif strcmp(op,'yview')

            el = 0;
            if ydir == 1
               az = 270;
            else
               az = 90;
            end

         elseif strcmp(op,'az-')

            az = az-val;

         elseif strcmp(op,'az+')

            az = az+val;

         elseif strcmp(op,'el-')

            el = el-val;

         elseif strcmp(op,'el+')

            el = el+val;

         elseif strcmp(op,'rst')

            el = 30;
            if [xdir ydir] == [1 1]
               az = -140;
            else
               az = 40;
            end

            set(h,'Value',10)

         end

         view(az,el)

         viewcontrols axislabels

      end

   end

end
