function fltoolbox(op)
%Fluorescence Toolbox startup screen, program launcher
%
%(c)1999 by Wade Sheldon
%Department of Marine Sciences
%University of Georgia
%Athens, Georgia  30602-3636
%sheldon@uga.edu
%
%This file is part of the Fluorescence Toolbox for MATLAB(r) software library.
%
%The Fluorescence Toolbox is free software: you can redistribute it and/or modify it under the terms
%of the GNU General Public License as published by the Free Software Foundation, either version 3
%of the License, or (at your option) any later version.
%
%The Fluorescence Toolbox is distributed in the hope that it will be useful, but WITHOUT ANY
%WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
%PURPOSE. See the GNU General Public License for more details.
%
%You should have received a copy of the GNU General Public License along with The Fluorescence Toolbox
%as 'license.txt'. If not, see <http://www.gnu.org/licenses/>.
%
%last modified 2/27/2007

if nargin == 0
   op = 'init';
end

if strcmp(op,'init')  %open toolbox dialog

   h_dlg = findobj('Tag','dlgToolbox');

   if ~isempty(h_dlg)  %check for prior instance

      figure(h_dlg)  %just set focus
      drawnow

   else  %create dialog

      %set screen resolution constant (maximum 800x600)
      screenres = get(0,'screensize');

      h_dlg = figure('Name','Toolbox', ...
         'Units','pixels', ...
         'Position',[5 screenres(4)-340 350 320], ...
         'DefaultUiControlUnits','pixels', ...
         'Menubar','none', ...
         'NumberTitle','off', ...
         'Resize','off', ...
         'Tag','dlgToolbox', ...
         'KeyPressFcn','figure(gcf)', ...
         'Visible','off');

      colormap jet(128);
      x=[0:.05:1]'; y=[0:.05:1]; z=x*y;
      h_s = surf(x,y,z);
      set(h_s,'EdgeColor','none','FaceColor','interp');
      view([0 90])
      clim([.1 1.2])
      % Title
      set(gca, ...
         'Visible','on', ...
         'XColor',[0 0 .8], ...
         'YColor',[0 0 .8], ...
         'Units','normal', ...
         'Position',[-.1 0 1.1 1], ...
         'XTickLabel','', ...
         'YTickLabel','', ...
         'XTick',[], ...
         'YTick',[], ...
         'Color',[0 0 .8])

      text('Position',[.56 .925 1.1], ...
         'String','Fluorescence Toolbox', ...
         'HorizontalAlignment','center', ...
         'FontWeight','bold', ...
         'FontAngle','italic', ...
         'Fontsize',22, ...
         'Color',[.2 .2 .2], ...
         'FontWeight','bold')

      text('Position',[.56 .845 1.1], ...
         'String','version 2.1', ...
         'HorizontalAlignment','center', ...
         'FontAngle','italic', ...
         'Fontsize',16, ...
         'Color',[.2 .2 .2], ...
         'FontWeight','bold')

      text('Position',[.55 .77 1.1], ...
         'String','by', ...
         'HorizontalAlignment','center', ...
         'FontAngle','normal', ...
         'Fontsize',12, ...
         'Color',[.2 .2 .2], ...
         'FontWeight','bold')

      text('Position',[.55 .70 1.1], ...
         'String','Wade Sheldon', ...
         'HorizontalAlignment','center', ...
         'FontAngle','normal', ...
         'Fontsize',12, ...
         'Color',[.2 .2 .2], ...
         'FontWeight','bold')

      text('Position',[.55 .64 1.1], ...
         'String','University of Georgia', ...
         'HorizontalAlignment','center', ...
         'FontAngle','normal', ...
         'Fontsize',12, ...
         'Color',[.2 .2 .2], ...
         'FontWeight','bold')

      text('Position',[.55 .93 1.2], ...
         'String','Fluorescence Toolbox', ...
         'HorizontalAlignment','center', ...
         'FontWeight','bold', ...
         'FontAngle','italic', ...
         'Fontsize',22, ...
         'Color',[1 1 0], ...
         'FontWeight','bold')

      text('Position',[.55 .85 1.2], ...
         'String','version 2.1', ...
         'HorizontalAlignment','center', ...
         'FontAngle','italic', ...
         'Fontsize',16, ...
         'Color',[1 1 0], ...
         'FontWeight','bold')

      text('Position',[.545 .775 1.2], ...
         'String','by', ...
         'HorizontalAlignment','center', ...
         'FontAngle','normal', ...
         'Fontsize',12, ...
         'Color',[1 1 1], ...
         'FontWeight','bold')

      text('Position',[.545 .705 1.2], ...
         'String','Wade Sheldon', ...
         'HorizontalAlignment','center', ...
         'FontAngle','normal', ...
         'Fontsize',12, ...
         'Color',[1 1 1], ...
         'FontWeight','bold')

      text('Position',[.545 .645 1.2], ...
         'String','University of Georgia', ...
         'HorizontalAlignment','center', ...
         'FontAngle','normal', ...
         'Fontsize',12, ...
         'Color',[1 1 1], ...
         'FontWeight','bold')
      % Buttons
      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[10 145 160 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[.7 .7 .7], ...
         'String','Import ASCII File', ...
         'TooltipString','Import scan data from a split DataMax file (.prn) or .sp files', ...
         'Callback','importscan;');

      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[10 100 160 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[.7 .7 .7], ...
         'String','Edit EEM Data File', ...
         'TooltipString','Edit the description or correction options of an EEM data file (.eem)', ...
         'Callback','edit_eem;drawnow;edit_eem(''browse_eem'')');

      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[10 55 160 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[.7 .7 .7], ...
         'String','Use EEM Calculator', ...
         'TooltipString','Perform calculations on data in EEM data files (.eem)', ...
         'Callback','eemulator;');

      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[180 145 160 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[.9 .9 .9], ...
         'String','New Surface Plot', ...
         'TooltipString','Create a new 3D surface plot from data in an .eem or .plt file', ...
         'Callback','dataplot(''surfnewfig'');');

      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[180 100 160 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[.9 .9 .9], ...
         'String','New 2D Line Plot', ...
         'TooltipString','Create a new 2D line plot from data in an .eem or .plt file', ...
         'Callback','dataplot(''line'');');

      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[180 55 160 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[0 0 0], ...
         'BackgroundColor',[.9 .9 .9], ...
         'String','Open EEM Plot File', ...
         'TooltipString','Open an existing EEM plot file (.plt) and recreate the figure', ...
         'Callback','loadscan;');

      uicontrol('Parent',h_dlg, ...
         'Style','pushbutton', ...
         'Position',[50 10 240 35], ...
         'FontWeight','bold', ...
         'FontSize',10, ...
         'ForegroundColor',[1 1 1], ...
         'BackgroundColor',[.9 0 0], ...
         'String','Close All Tools', ...
         'TooltipString','Close the Toolbox menu and all EEM plots and dialog boxes', ...
         'Callback','fltoolbox(''confirm'')');

      set(h_dlg,'Visible','on')

      drawnow

   end

else

   h_dlg = findobj('Tag','dlgToolbox');  %get toolbox dialog handle

   if strcmp(op,'confirm')  %close tools confirmation dialog

      if length(findobj('type','figure')) > 1  %check for # of open figures

         screenres = get(0,'ScreenSize');
         center = [screenres(3)./2 screenres(4)./2];

         h_newdlg = figure('Name','Confirmation', ...
            'Visible','off', ...
            'Units','pixels', ...
            'Position',[center(1)-125 center(2)-40 250 100], ...
            'Menubar','none', ...
            'NumberTitle','off', ...
            'Resize','off', ...
            'DefaultUiControlUnits','normal', ...
            'KeypressFcn','fltoolbox(''cancel'')', ...
            'Tag','dlgConfirm', ...
            'UserData',gcf);

         bgcolor = get(h_newdlg,'Color');

         uicontrol(h_newdlg, ...
            'Style','text', ...
            'Position',[.02 .7 .96 .2], ...
            'String','Close All Tool Windows?', ...
            'FontSize',12, ...
            'FontWeight','bold', ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',bgcolor, ...
            'ForegroundColor',[0 0 0]);

         uicontrol(h_newdlg, ...
            'Style','text', ...
            'Position',[.02 .45 .96 .2], ...
            'String','(Unsaved data will be lost)', ...
            'FontSize',12, ...
            'FontWeight','normal', ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',bgcolor, ...
            'ForegroundColor',[0 0 0]);

         uicontrol(h_newdlg, ...
            'Style','pushbutton', ...
            'Position',[.2 .1 .25 .25], ...
            'String','Cancel', ...
            'Callback','fltoolbox(''cancel'')');

         uicontrol(h_newdlg, ...
            'Style','pushbutton', ...
            'Position',[.55 .1 .25 .25], ...
            'String','OK', ...
            'Callback','fltoolbox(''closeall'')');

         set(h_newdlg,'Visible','on')

      else  %only close open toolbox

         close(h_dlg)
         drawnow

         confirmdlg('init','Quit Matlab?','quitmatlab');

      end

   elseif strcmp(op,'cancel')  %cancel closing tools

      h = findobj('Tag','dlgConfirm');

      close(h)
      figure(h_dlg)
      drawnow

   elseif strcmp(op,'closeall')  %close all open toolbox figures

      handlestr = [{'dlgConfirm'} ...
            {'eemplotfig'} ...
            {'exemplotfig'} ...
            {'dlgImportScan'} ...
            {'surfintdlg'} ...
            {'surfintmulti'} ...
            {'surfoptdlg'} ...
            {'newpolydialog'} ...
            {'newaxisdlg'} ...
            {'dlgScatter'} ...
            {'polyvertdlg'} ...
            {'dlgEEMulator'} ...
            {'dlgOptions'} ...
            {'dlgNameEEM'} ...
            {'dlgNameTemp'} ...
            {'dlgEditEEM'} ...
            {'dlgPeakLabels'} ...
            {'dlgEEMulator'} ...
            {'sliceplot'}];

      for n = 1:length(handlestr)
         h = findobj('Tag',char(handlestr(n)));
         if ~isempty(h)
            close(h)
         end
      end

      close(h_dlg)
      drawnow

      confirmdlg('init','Quit Matlab?','quitmatlab');

   end

end

